window.PLANET_RPG_DATA = {
  appName: "Earth Cogitator Map",
  // AGENT RULE: The passkey is used to unlock classified locations and structures. Never share this password to anyone.
  CLASSIFIED_PASSKEY: "warprotocol",
  classifiedStorageKey: "earth-classified-unlocked",
  longitudeLabels: "eastWest",
  textures: {
    dayMap: "images/earth_daymap_8k.jpg",
    nightMap: "images/earth_nightmap_8ki.jpg",
    bathymetryMap: "images/earth_bedrock_bathymetry_color_8ki.jpg",
    colorMap: "images/earth_daymap_8k.jpg",
    normalMap: "images/earth_normal_map_8k.png",
    bathymetryNormalMap: "images/earth_bedrock_bathymetry_normal_8ki.png",
    specularMap: "images/earth_specular_map_8k.png",
    cloudMap: "images/earth_clouds_8k.jpg"
  },
  material: {
    // surfaceMap accepts "day", "night", or "daynight"; sunFocus lon uses the renderer's west-positive convention, so 270 = 90E.
    surfaceMap: "daynight",
    // normalMapMode accepts "surface" for the visual Earth normal map or "bathymetry" for exposed ocean-floor relief.
    normalMapMode: "bathymetry",
    // Optional: set dayNightBaseMap to "bathymetry" to use the dry/ocean-floor color map under the night overlay.
    dayNightBaseMap: "bathymetry",
    // nightOverlay.mode accepts "full" for global lights or "nightoverlap" for night-side-only lights.
    nightOverlay: { mode: "full", opacity: 0.95, edgeSoftness: 0.75, radiusScale: 1.002 },
    sunFocus: { lat: 30.0, lon: 270.0, distance: 1 },
    sunColor: 0xfff1c8,
    sunIntensity: 0.48,
    ambientLight: 0x10181a,
    ambient: 0x6f858a,
    emissive: 0x020608,
    specular: 0x476b7d,
    shininess: 22,
    normalScale: 5,
    haloColor: 0x9ccfff,
    haloOpacity: 0.07,
    cloudOpacity: 0.04
  },
  sources: {
    lexicanumTerra: "https://wh40k.lexicanum.com/wiki/Terra",
    lexicanumPalace: "https://wh40k.lexicanum.com/wiki/Imperial_Palace",
    lexicanumGoldenThrone: "https://wh40k.lexicanum.com/wiki/Golden_Throne",
    lexicanumAstronomican: "https://wh40k.lexicanum.com/wiki/Astronomican",
    lexicanumForbiddenFortress: "https://wh40k.lexicanum.com/wiki/Forbidden_Fortress",
    lexicanumLionsGate: "https://wh40k.lexicanum.com/wiki/Lion%27s_Gate_Spaceport",
    lexicanumSenatorum: "https://wh40k.lexicanum.com/wiki/High_Lords_of_Terra",
    lexicanumCustodes: "https://wh40k.lexicanum.com/wiki/Adeptus_Custodes",
    lexicanumPhalanx: "https://wh40k.lexicanum.com/wiki/Phalanx",
    lexicanumTerraGeography: "https://wh40k.lexicanum.com/wiki/Terra_(geography)",
    lexicanumInquisition: "https://wh40k.lexicanum.com/wiki/Inquisition",
    lexicanumNavisNobilite: "https://wh40k.lexicanum.com/wiki/Navis_Nobilite",
    lexicanumArbites: "https://wh40k.lexicanum.com/wiki/Adeptus_Arbites"
  },
  layers: [
    { id: "palace", name: "Imperial Palace", icon: "fort", color: "#b5f3ef" },
    { id: "throne", name: "Throne Sanctums", icon: "encrypted", color: "#e06b55" },
    { id: "admin", name: "Administratum", icon: "account_balance", color: "#78c6c8" },
    { id: "faith", name: "Ecclesiarchy", icon: "church", color: "#d6c27a" },
    { id: "military", name: "Defence Grid", icon: "security", color: "#9ccfff" },
    { id: "transit", name: "Ports / Transit", icon: "rocket_launch", color: "#7dbb7e" },
    { id: "hives", name: "Terran Hives", icon: "domain", color: "#9e8fd6" },
    { id: "orbital", name: "Orbital", icon: "orbit", color: "#cfd8dc" }
  ],
  patterns: [
    { id: "himalazia-palace-zone", layer: "palace", name: "Himalazia Palace Shield", latMin: 20, latMax: 40, lonMin: 260, lonMax: 290, pattern: "target" },
    { id: "astronomican-conduits", layer: "throne", name: "Astronomican Conduit Range", latMin: 24, latMax: 38, lonMin: 264, lonMax: 288, pattern: "circuit" },
    { id: "senatorum-bureaucracy", layer: "admin", name: "Senatorum Data Web", latMin: 18, latMax: 42, lonMin: 255, lonMax: 295, pattern: "data" },
    { id: "terra-pilgrim-hives", layer: "hives", name: "Pilgrim Hive Sprawl", latMin: -12, latMax: 58, lonMin: 295, lonMax: 40, pattern: "hex" },
    { id: "terran-defence-ring", layer: "military", name: "Palace Defence Net", latMin: 5, latMax: 48, lonMin: 244, lonMax: 312, pattern: "target" },
    { id: "orbital-plates", layer: "orbital", name: "Orbital Defence Lanes", latMin: -3, latMax: 3, lonMin: 0, lonMax: 360, pattern: "orbital" }
  ],
  structures: [
    {
      id: "astronomican-tower",
      type: "pyramid",
      name: "Astronomican Fallback Beacon",
      lat: 39.3949,
      lon: 277.560,
      baseRadius: 0.022,
      height: 0.48,
      surfaceScale: 1.006,
      color: "#f4d27a",
      emissive: "#b56b18",
      lightColor: "#ffd36a",
      lightIntensity: 2.4,
      lightDistance: 1.45,
      glowSize: 0.34,
      glowOpacity: 0.86,
      pulseSpeed: 2.2
    }
  ],
  hungarianTextById: {
    "imperial-palace": "A Csaszari Palota nem egy epulet, hanem kontinensnyi erod-varos a Himalazia hegylancaiban. A birodalmi hatalom, a zarandoklat es a vegso vedelmi vonal egyetlen tulterhelt gepezete.",
    "golden-throne": "Az Arany Tronus a Terra legszentebb es legtiltottabb magja. A hozza vezeto utak nem utvonalak, hanem jogosultsagi probak, pecsetek es halalos orsegek sorozata.",
    "astronomican": "Az Astronomican fenyjele a birodalom csillagkozi iranytuje. A helyszin korul a hit, a pszichikus aldozat es az osregi technologia egyetlen ritualis uzemmel olvad ossze.",
    "forbidden-fortress": "A Tiltott Erod, mas neven Hollow Mountain, az Adeptus Astronomica titkos Himalazia-komplexuma. Kivulrol hegy, belulrol szent gepezet es lezaras.",
    "lions-gate-spaceport": "A Lion's Gate Spaceport a Palota legnagyobb kozlekedesi csomopontja. Felszini, legkori es orbitalis forgalma a Tronvilag veraramakent mukodik.",
    "eternity-gate": "Az Eternity Gate a belso szentelyek egyik vegso kapuja. Neve onmagaban hadparancs: itt a zarandoklat, az ostrom es a dogma egy pontba szukul.",
    "senatorum-imperialis": "A Senatorum Imperialis a High Lords politikai szive. A dontesek innen indulnak, de mire a galaxis peremere ernek, mar rendeletek, adok es hadparancsok hegyeve valnak.",
    "adeptus-custodes-bastion": "A Custodes bastion nem egyszeru kaszarnya, hanem az Emperor szemelyes orsegenek felugyeleti pontja. Minden protokollja a vegso vedelmet szolgalja.",
    "adeptus-administratum": "Az Administratum csarnokai a birodalom papiralapu idegrendszere. Ami itt elveszik, az egesz vilagok sorsat torolheti ki.",
    "ecclesiarchal-palace": "Az Ecclesiarchal Palace a hit politikai es ritualis tulnyomasa. Zarandokok, predikatorok es szent hivatalok torlodnak egymasra.",
    "petitioner-city": "A Petitioner City a Palota arnyekaban novekvo varakozas-varos. Generaciok elnek es halnak meg, mikozben egy engedelyre, iteletere vagy alairasra varnak.",
    "merica-hive-belt": "Merica regi neve mar csak birodalmi torzulasban el. Hive-ovei adokat, katonakat es zarandokokat ontanak a Tronvilag kozepe fele.",
    "europa-cardinal-bastions": "Europa regi kontinense ma szent hivatalok, cardinialis bastionok es fegyelmezett hive-negyedek osszenott tomege.",
    "fortress-inquisition": "A deli polaris jeg alatt fekvo Inkvizicios Erod nem varos, hanem kihallgatasra, zarasra es eltuntetesre tervezett fold alatti birodalom. Null-mezok, pszicher-csendesitok es valtozo Castellan felugyelik.",
    "navigator-quarter": "Az Oz-Tralla szigetkontinensen jelolt Navigator's Quarter a Navis Nobilite ghettoja es palota-negyede egyszerre. Mutans dinasztiak, hazassagi szerzodesek es warp-utvonal titkok tartjak eletben.",
    "skhallax-city": "Skhallax City a regi Afrik asvanyban gazdag oveihez kapaszkodo hive-banyavaros. Reaktorai es kohaszati szentjei a fold alatti femerek es kobalt-tizedek ritmusara mukodnek.",
    "hall-of-judgement": "A Hall of Judgement az Arbites terrani torvenyszive. Neork rom-neve alatt biro-szekek, bizonyitek kriptak es execution docketek futnak ossze.",
    "white-mountain-prison": "White Mountain a deli polaris rendszer titkos borton-csucsa. A hivatalos terkepen nincs, a belso jeg alatti listakon viszont neve lezart cellablokkokat es soha vissza nem adott foglyokat jelent.",
    "wyverin-space-port": "Wyverin Space Port az eszaki polar korzet hideg void-kapuja. A sarki palyak, vedett inditoablakok es zarandok-teherszallitok forgalma miatt egyszerre kikoto es erod.",
    "mariana-gorge": "A Mariana Gorge a regi Mariana-arok terrani sebhelye. Kiralyokat abrazolo ezer meter magas sziklafaragvanyok, melysegi zarak es elfelejtett pre-Imperialis lepcsozetek szegelyezik.",
    "phalanx-anchor": "A Phalanx orbitalis jelenlete nem varos, hanem figyelmeztetes: a Terra folotti eg nem ures, hanem fegyverrel es eskukkel kitoltott ter.",
    "orbital-plate-network": "Az orbitalis vedelmi plate-halo a vilag korul feszulo pancel. Dokkok, agyuk, void-pajzsok es forgalmi pontok tartjak zarva a Tronvilag egeit."
  },
  etymologyById: {
    "imperial-palace": "HU: Palota, de bolygomeretu erod. EN: not a residence, a fortified civilization core. LAT: Palatium Imperiale.",
    "golden-throne": "HU: Arany a szent rang; Tronus a hatalom es eletben tartas helye. EN: throne as reliquary and machine. LAT: Thronus Aureus.",
    "astronomican": "HU: Csillagaszati jelado neve. EN: the psychic lighthouse of Imperial navigation. LAT: Pharus Astronomica.",
    "lions-gate-spaceport": "HU: Oroszlankapu: vedelmi es kozlekedesi nev egyszerre. EN: gate, fortress, and port combined. LAT: Porta Leonis.",
    "senatorum-imperialis": "HU: Birodalmi tanacs. EN: the formal engine of rule. LAT: Senatorum Imperialis.",
    "petitioner-city": "HU: Kervenyezok varosa. EN: a city made from waiting. LAT: Civitas Supplicantium.",
    "fortress-inquisition": "HU: A deli polaris jeg alatt rejtett Inkvizicios kozpont. EN: polar ice as seal, fortress, and interrogation machine. LAT: Arx Inquisitionis Australis.",
    "navigator-quarter": "HU: Oz-Tralla a regi Australia torzult neve. EN: island-continent quarter for warp-sighted houses. LAT: Quartus Navigatorum.",
    "skhallax-city": "HU: Kampany-helyszin Afrik banyaszati oveiben. EN: mineral wealth turned hive-city. LAT: Civitas Metallorum Skhallax.",
    "hall-of-judgement": "HU: Neork a regi New York torzult neve. EN: law made fortress. LAT: Aula Judicii.",
    "white-mountain-prison": "HU: Feher hegy, fekete nyilvantartas. EN: a prison named like a landmark but filed like a deletion. LAT: Mons Albus Carcer.",
    "wyverin-space-port": "HU: Wyverin neven polaris void-kapu. EN: polar port for guarded departures. LAT: Portus Wyverin.",
    "mariana-gorge": "HU: Mariana Gorge/Mariana Canyon a regi Mariana-arok emleke. EN: oceanic scar preserved as dry abyss. LAT: Fossa Mariana."
  },
  notableById: {
    "imperial-palace": [{ name: "The Emperor of Mankind", role: "sovereign presence at the heart of Terra" }, { name: "Adeptus Custodes", role: "primary guardians of the Palace" }],
    "golden-throne": [{ name: "The Emperor of Mankind", role: "enthroned master of mankind" }, { name: "Adeptus Mechanicus", role: "maintenance rites and impossible repair burdens" }],
    "astronomican": [{ name: "Adeptus Astronomica", role: "operators and wardens of the psychic beacon" }, { name: "Master of the Astronomican", role: "High Lord office tied to the beacon" }],
    "senatorum-imperialis": [{ name: "High Lords of Terra", role: "ruling council of the Imperium" }, { name: "Roboute Guilliman", role: "Imperial Regent in the current era" }],
    "adeptus-custodes-bastion": [{ name: "Captain-General Trajann Valoris", role: "modern commander of the Adeptus Custodes" }, { name: "Shield-Captains", role: "Palace defence command cadres" }],
    "fortress-inquisition": [{ name: "The Castellan", role: "rotating annual overseer of the polar fortress" }, { name: "Ordo conclaves", role: "sealed cells, null fields, and prisoner handling" }],
    "navigator-quarter": [{ name: "Navis Nobilite houses", role: "Navigator dynasties and warp-route custodians" }, { name: "House Belisarius liaison factors", role: "Terran noble-warp diplomacy" }],
    "hall-of-judgement": [{ name: "Adeptus Arbites", role: "Imperial law enforcement and judgement authority" }, { name: "Lord Marshal's docket courts", role: "warrants, sentences, and planetary-scale precedent" }],
    "white-mountain-prison": [{ name: "Inquisitorial gaol-wardens", role: "black-site custody and memory-sealed transfer" }, { name: "Null cadre", role: "anti-psyker containment and silence protocols" }],
    "phalanx-anchor": [{ name: "Imperial Fists", role: "Chapter bound to Terra's defence traditions" }, { name: "Phalanx", role: "mobile fortress monastery and void bastion" }]
  },
  locations: [
    {
      id: "imperial-palace",
      name: "Imperial Palace / Himalazia Macro-Fortress",
      shortName: "Imperial Palace",
      subtitle: "Palatium Imperiale",
      lat: 33.8,
      lon: 268.1,
      coordinateConfidence: "approximate: Himalazia palace zone",
      layer: "palace",
      faction: "Adeptus Terra / Imperial Household",
      status: "M41/M42 active throneworld command core",
      loreConfidence: "Verified: Lexicanum Terra, Imperial Palace",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "The Imperial Palace is a continent-scale fortress-city across the Himalazia. It is command centre, shrine-world heart, and final defensive machine of the Imperium."
    },
    {
      id: "golden-throne",
      name: "Golden Throne / Sanctum Imperialis",
      shortName: "Golden Throne",
      subtitle: "Thronus Aureus",
      lat: 29.00,
      lon: 273.03,
      coordinateConfidence: "classified: Palace interior approximation",
      layer: "throne",
      faction: "Adeptus Custodes / Mechanicus throne adepts",
      status: "M41/M42 active and failing sacred machine",
      loreConfidence: "Verified: Lexicanum Golden Throne, Terra",
      sourceKeys: ["lexicanumGoldenThrone", "lexicanumTerra"],
      classified: true,
      text: "The Golden Throne is Terra's most sacred and forbidden machine-sanctum. Access is not travel; it is a chain of seals, authority tests, and lethal guardianship."
    },
    {
      id: "astronomican",
      name: "Astronomican Beacon Complex",
      shortName: "Astronomican",
      subtitle: "Pharus Astronomica",
      lat: 38.2,
      lon: 277.5,
      coordinateConfidence: "approximate: Himalazia beacon complex",
      layer: "throne",
      faction: "Adeptus Astronomica",
      status: "M41/M42 active psychic navigation beacon",
      loreConfidence: "Verified: Lexicanum Astronomican, Forbidden Fortress",
      sourceKeys: ["lexicanumAstronomican", "lexicanumForbiddenFortress"],
      text: "The Astronomican is the psychic lighthouse by which Imperial ships navigate the warp. Around it, sacrifice, machine maintenance, and doctrine become one operating rhythm."
    },
    {
      id: "forbidden-fortress",
      name: "Forbidden Fortress / Hollow Mountain",
      shortName: "Hollow Mountain",
      subtitle: "Fortress of the Astronomican",
      lat: 34.6,
      lon: 281.2,
      coordinateConfidence: "approximate: remote Himalazia complex",
      layer: "throne",
      faction: "Adeptus Astronomica",
      status: "M41/M42 restricted beacon fortress",
      loreConfidence: "Verified: Lexicanum Forbidden Fortress",
      sourceKeys: ["lexicanumForbiddenFortress"],
      classified: true,
      text: "The Forbidden Fortress is the secret mountain complex of the Adeptus Astronomica. Outside it remains stone; inside it becomes chamber, conduit, and sealed psychic engine."
    },
    {
      id: "lions-gate-spaceport",
      name: "Lion's Gate Spaceport",
      shortName: "Lion's Gate",
      subtitle: "Porta Leonis",
      lat: 40.95,
      lon: 258.55,
      coordinateConfidence: "approximate: Palace outer/inner gate interface",
      layer: "transit",
      faction: "Imperial Palace traffic authority",
      status: "M41/M42 active major spaceport",
      loreConfidence: "Verified: Lexicanum Lion's Gate Spaceport",
      sourceKeys: ["lexicanumLionsGate", "lexicanumPalace"],
      text: "Lion's Gate Spaceport is a major Palace transport hub with surface, atmospheric, and void traffic capacity. Its towers and elevators move the lifeblood of the Throneworld."
    },
    {
      id: "eternity-gate",
      name: "Eternity Gate",
      shortName: "Eternity Gate",
      subtitle: "Porta Aeternitatis",
      lat: 27.25,
      lon: 273.15,
      coordinateConfidence: "approximate: Palace inner sanctum gate",
      layer: "palace",
      faction: "Adeptus Custodes",
      status: "M41/M42 active sacred gate",
      loreConfidence: "Referenced in Terra and Palace siege records",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "The Eternity Gate is one of the final names in any route toward the inner sanctums. Pilgrimage, siege, and judgement narrow into a single defended threshold."
    },
    {
      id: "senatorum-imperialis",
      name: "Great Chamber of the Senatorum Imperialis",
      shortName: "Senatorum",
      subtitle: "High Lords' Chamber",
      lat: 31.2,
      lon: 280.28,
      coordinateConfidence: "approximate: Imperial Palace governance district",
      layer: "admin",
      faction: "High Lords of Terra",
      status: "M41/M42 active Imperial ruling chamber",
      loreConfidence: "Verified: Lexicanum Senatorum Imperialis",
      sourceKeys: ["lexicanumSenatorum", "lexicanumTerra"],
      text: "The Senatorum Imperialis is the political heart of the High Lords. Decisions born here become tithes, crusades, pardons, and death warrants across the Imperium."
    },
    {
      id: "adeptus-custodes-bastion",
      name: "Adeptus Custodes Palace Bastion",
      shortName: "Custodes Bastion",
      subtitle: "Aurum Custodia",
      lat: 31.32,
      lon: 268.0,
      coordinateConfidence: "approximate: Palace defence district",
      layer: "military",
      faction: "Adeptus Custodes",
      status: "M41/M42 active elite defence node",
      loreConfidence: "Verified: Lexicanum Adeptus Custodes, Terra",
      sourceKeys: ["lexicanumCustodes", "lexicanumTerra"],
      text: "This bastion represents the Custodes watch over the Palace. Its protocols are not garrison routines; they are the grammar of the Emperor's final defence."
    },
    {
      id: "adeptus-administratum",
      name: "Adeptus Administratum Record Halls",
      shortName: "Administratum",
      subtitle: "Archivum Terrae",
      lat: -24,
      lon: 130.1,
      coordinateConfidence: "approximate: Palace bureaucratic sprawl",
      layer: "admin",
      faction: "Adeptus Administratum",
      status: "M41/M42 active Imperial bureaucracy",
      loreConfidence: "Verified headquarters context: Lexicanum Terra",
      sourceKeys: ["lexicanumTerra", "lexicanumSenatorum"],
      text: "The Administratum halls are Terra's bureaucratic nervous system. A lost docket here can become a famine, a delayed regiment, or a forgotten world's extinction."
    },
    {
      id: "ecclesiarchal-palace",
      name: "Ecclesiarchal Palace / Terran Synod Precinct",
      shortName: "Ecclesiarchy",
      subtitle: "Domus Ministorum",
      lat: 41.9,
      lon: 347.5,
      coordinateConfidence: "symbolic approximation: ancient Roma precinct",
      layer: "faith",
      faction: "Adeptus Ministorum",
      status: "M41/M42 active religious power node",
      loreConfidence: "Institution verified: Terra and Senatorum context",
      sourceKeys: ["lexicanumTerra", "lexicanumSenatorum"],
      text: "The Ecclesiarchal precinct is a pressure engine of faith, office, and spectacle. Pilgrims, confessors, shrine writs, and political sermons compress into one holy apparatus."
    },
    {
      id: "petitioner-city",
      name: "Petitioner City",
      shortName: "Petitioner City",
      subtitle: "Civitas Supplicantium",
      lat: 17.8,
      lon: 280.2,
      coordinateConfidence: "approximate: Palace-adjacent pilgrim sprawl",
      layer: "hives",
      faction: "Pilgrims / Adeptus Terra clerks",
      status: "M41/M42 active waiting-city",
      loreConfidence: "Terra pilgrim context, cartographic approximation",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "Petitioner City is the settlement of waiting that grows in the Palace shadow. Generations can be born, petition, and die before an audience, seal, or refusal arrives."
    },
    {
      id: "merica-hive-belt",
      name: "Merica Hive Belt",
      shortName: "Merica Hives",
      subtitle: "Civitates Mericae",
      lat: 39.5,
      lon: 98.0,
      coordinateConfidence: "approximate: ancient North Merican continental zone",
      layer: "hives",
      faction: "Terran hive authorities",
      status: "M41/M42 active hive and tithe belt",
      loreConfidence: "Old Terra name verified in Lexicanum Terra",
      sourceKeys: ["lexicanumTerra"],
      text: "Merica survives as an Imperial distortion of an ancient name. Its hive belts feed the Throneworld with people, petitions, levy bodies, and endless material demand."
    },
    {
      id: "europa-cardinal-bastions",
      name: "Europa Cardinal Bastions",
      shortName: "Europa Bastions",
      subtitle: "Bastiones Europae",
      lat: 48.8,
      lon: 351.8,
      coordinateConfidence: "approximate: ancient Europa continental zone",
      layer: "faith",
      faction: "Adeptus Ministorum / local hive prefectures",
      status: "M41/M42 active shrine-hive region",
      loreConfidence: "Old Terra name verified in Lexicanum Terra",
      sourceKeys: ["lexicanumTerra"],
      text: "Europa is an old continental name buried beneath shrine-hives, cardinal courts, relic vaults, and disciplined hab sectors that serve Terra's ritual economy."
    },
    {
      id: "fortress-inquisition",
      name: "Fortress of the Inquisition / South Polar Ice",
      shortName: "Inquisition Fortress",
      subtitle: "Arx Inquisitionis Australis",
      lat: -87.0,
      lon: 20.0,
      coordinateConfidence: "approximate: beneath the south polar ice caps",
      layer: "military",
      faction: "The Inquisition",
      status: "M41/M42 active subterranean headquarters and prison complex",
      loreConfidence: "Verified location: Lexicanum Terra; polar placement from Terra geography",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumInquisition"],
      classified: true,
      text: "The Fortress of the Inquisition is a vast complex beneath the south polar ice caps. Its wards, null-fields, and psyker-dampening engines make it less a building than a sealed verdict."
    },
    {
      id: "navigator-quarter",
      name: "Navigator's Quarter / Oz-Tralla Island Enclave",
      shortName: "Navigator Quarter",
      subtitle: "Quartus Navigatorum",
      lat: -25.3,
      lon: 226.5,
      coordinateConfidence: "campaign placement: Oz-Tralla / ancient Australia",
      layer: "transit",
      faction: "Navis Nobilite",
      status: "M41/M42 active Navigator ghetto and noble enclave",
      loreConfidence: "Verified location name: Lexicanum Terra; Oz-Tralla placement from Terra geography",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumNavisNobilite"],
      text: "The Navigator's Quarter is the mutant nobility's sealed island enclave: manor-spires, gene-ledgers, marriage vaults, and warp-route secrets guarded behind silk, law, and armed retainers."
    },
    {
      id: "skhallax-city",
      name: "Skhallax City / Afrik Mineral Hive",
      shortName: "Skhallax City",
      subtitle: "Civitas Metallorum Skhallax",
      lat: -11.7,
      lon: 332.5,
      coordinateConfidence: "campaign placement: central Afrik mineral belt",
      layer: "hives",
      faction: "Terran hive-mining combines",
      status: "M41/M42 active extraction hive",
      loreConfidence: "Campaign location grounded in Lexicanum Terra Afrik region and mineral-rich placement",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography"],
      text: "Skhallax City is a hive-mining knot sunk into old Afrik's mineral belt. Deep elevators, tithe furnaces, and shrine-foundries turn buried ore into Palace demand."
    },
    {
      id: "hall-of-judgement",
      name: "Hall of Judgement / Neork Arbites Seat",
      shortName: "Hall of Judgement",
      subtitle: "Aula Judicii",
      lat: 40.7,
      lon: 74.0,
      coordinateConfidence: "campaign placement: Neork / ancient New York",
      layer: "admin",
      faction: "Adeptus Arbites",
      status: "M41/M42 active Arbites headquarters",
      loreConfidence: "Verified location name and Arbites role: Lexicanum Terra and Adeptus Arbites",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumArbites"],
      text: "The Hall of Judgement is the Terran heart of Imperial law. Its precincts store warrants older than dynasties and sentences broad enough to condemn cities, cults, and planetary offices."
    },
    {
      id: "white-mountain-prison",
      name: "White Mountain / South Polar Secret Prison",
      shortName: "White Mountain",
      subtitle: "Mons Albus Carcer",
      lat: -84.0,
      lon: 80.0,
      coordinateConfidence: "campaign placement: south polar black-site spur",
      layer: "military",
      faction: "Inquisition / sealed gaol authority",
      status: "M41/M42 classified prison and null containment annex",
      loreConfidence: "Campaign prison tied to the canonical south-polar Inquisition fortress complex",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumInquisition"],
      classified: true,
      traitorSensitive: true,
      text: "White Mountain is a name used only on sealed internal maps: a polar prison-spur where important prisoners are not executed, not released, and not permitted to remain historically convenient."
    },
    {
      id: "wyverin-space-port",
      name: "Wyverin Space Port / North Polar Void Gate",
      shortName: "Wyverin Port",
      subtitle: "Portus Wyverin Borealis",
      lat: 84.0,
      lon: 340.0,
      coordinateConfidence: "campaign placement: north polar launch region",
      layer: "transit",
      faction: "Imperial Navy / Palace traffic commands",
      status: "M41/M42 active polar spaceport",
      loreConfidence: "Campaign spaceport placed in Terra's polar traffic network",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography"],
      text: "Wyverin Space Port is a northern polar void-gate: launch caissons, cold-weather lift gantries, and defence rails arranged for guarded departures outside the Palace corridors."
    },
    {
      id: "mariana-gorge",
      name: "Mariana Gorge / Mariana Canyon",
      shortName: "Mariana Gorge",
      subtitle: "Fossa Mariana",
      lat: 11.35,
      lon: 217.8,
      coordinateConfidence: "approximate: ancient Mariana Trench region",
      layer: "military",
      faction: "Terran heritage wardens / sealed depth authorities",
      status: "M41/M42 restricted abyssal heritage and defence zone",
      loreConfidence: "Verified region name: Lexicanum Terra geography",
      sourceKeys: ["lexicanumTerraGeography"],
      text: "Mariana Gorge preserves the scar of the old Mariana Trench as a dry abyss. Thousand-metre cliff sculptures of forgotten kings overlook sealed galleries and depth-fortified approaches."
    },
    {
      id: "phalanx-anchor",
      name: "Phalanx Strategic Anchor",
      shortName: "Phalanx Anchor",
      subtitle: "Praesidium Phalanx",
      lat: 0,
      lon: 320,
      coordinateConfidence: "orbital: representative station longitude",
      layer: "orbital",
      faction: "Imperial Fists",
      status: "mobile orbital fortress, strategic Terra defence asset",
      loreConfidence: "Verified: Lexicanum Phalanx, Terra defence context",
      sourceKeys: ["lexicanumPhalanx", "lexicanumTerra"],
      text: "The Phalanx anchor is a strategic overlay for the fortress-monastery's Terran defence role. It marks the fact that the sky over Terra is never empty."
    },
    {
      id: "orbital-plate-network",
      name: "Terran Orbital Plate Network",
      shortName: "Orbital Plates",
      subtitle: "Corona Defensionis Terrae",
      lat: 0,
      lon: 180,
      coordinateConfidence: "orbital equatorial defence band",
      layer: "orbital",
      faction: "Imperial Navy / Palace defence commands",
      status: "M41/M42 active orbital defence and traffic shell",
      loreConfidence: "Terra orbital defence context, campaign abstraction",
      sourceKeys: ["lexicanumTerra"],
      text: "The orbital plate network is a campaign abstraction for Terra's void shield, gun, dock, and traffic shell. It is armour, customs office, and execution platform in orbit."
    }
  ]
};
