window.PLANET_RPG_DATA = {
  appName: "Earth Cogitator Map",
  // AGENT RULE: The passkey is used to unlock classified locations and structures. Never share this password to anyone.
  CLASSIFIED_PASSKEY: "warprotocol",
  classifiedStorageKey: "earth-classified-unlocked",
  longitudeLabels: "eastWest",
  markerStyle: { visible: false },
  textures: {
    dayMap: "images/earth_daymap_8k.jpg",
    nightMap: "images/earth_nightmap_8ki.jpg",
    bathymetryMap: "images/earth_bedrock_bathymetry_color_8ki.jpg",
    colorMap: "images/earth_daymap_8k.jpg",
    normalMap: {
      ktx2: "images/earth_normal_map_8k_uastc.ktx2",
      webp: "images/earth_normal_map_8k.webp",
      fallback: "images/earth_normal_map_8k.png"
    },
    bathymetryNormalMap: {
      ktx2: "images/earth_bedrock_bathymetry_normal_8ki_uastc.ktx2",
      webp: "images/earth_bedrock_bathymetry_normal_8ki.webp",
      fallback: "images/earth_bedrock_bathymetry_normal_8ki.png"
    },
    specularMap: "images/earth_specular_map_8k.png",
    cloudMap: "images/earth_clouds_8k.jpg"
  },
  material: {
    // surfaceMap accepts "day", "night", or "daynight"; sunFocus lon uses the renderer's west-positive convention, so 270 = 90E.
    surfaceMap: "daynight",
    // normalMapMode accepts "surface" for the visual Earth normal map or "bathymetry" for exposed ocean-floor relief.
    normalMapMode: "bathymetry",
    // Optional: set dayNightBaseMap to "bathymetry" to use the dry/ocean-floor color map under the night overlay.
    dayNightBaseMap: "bathymetry",
    // nightOverlay.mode accepts "full" for global lights or "nightoverlap" for night-side-only lights.
    nightOverlay: { mode: "full", opacity: 0.95, edgeSoftness: 0.75, radiusScale: 1.002 },
    nightGlow: { enabled: true, mode: "full", opacity: 10.52, threshold: 0.04, softness: 0.9, colorBoost: 0.40, radiusScale: 1.004 },
    bloom: { enabled: true, strength: 0.85, radius: 0.5, threshold: 0.56 },
    sunFocus: { lat: 30.0, lon: 270.0, distance: 1 },
    sunColor: 0xfff1c8,
    sunIntensity: 0.08,
    ambientLight: 0x10181a,
    ambient: 0x6f858a,
    emissive: 0x020608,
    specular: 0x476b7d,
    shininess: 2,
    normalScale: 10,
    haloColor: 0x9ccfff,
    haloOpacity: 0.07,
    cloudOpacity: 0.04
  },
  sources: {
    lexicanumTerra: "https://wh40k.lexicanum.com/wiki/Terra",
    lexicanumPalace: "https://wh40k.lexicanum.com/wiki/Imperial_Palace",
    lexicanumGoldenThrone: "https://wh40k.lexicanum.com/wiki/Golden_Throne",
    lexicanumAstronomican: "https://wh40k.lexicanum.com/wiki/Astronomican",
    lexicanumForbiddenFortress: "https://wh40k.lexicanum.com/wiki/Forbidden_Fortress",
    lexicanumLionsGate: "https://wh40k.lexicanum.com/wiki/Lion%27s_Gate_Spaceport",
    lexicanumSenatorum: "https://wh40k.lexicanum.com/wiki/High_Lords_of_Terra",
    lexicanumCustodes: "https://wh40k.lexicanum.com/wiki/Adeptus_Custodes",
    lexicanumPhalanx: "https://wh40k.lexicanum.com/wiki/Phalanx",
    lexicanumTerraGeography: "https://wh40k.lexicanum.com/wiki/Terra_(geography)",
    lexicanumInquisition: "https://wh40k.lexicanum.com/wiki/Inquisition",
    lexicanumNavisNobilite: "https://wh40k.lexicanum.com/wiki/Navis_Nobilite",
    lexicanumArbites: "https://wh40k.lexicanum.com/wiki/Adeptus_Arbites",
    lexicanumOfficioAssassinorum: "https://wh40k.lexicanum.com/wiki/Officio_Assassinorum",
    lexicanumLuna: "https://wh40k.lexicanum.com/wiki/Luna",
    lexicanumSomnusCitadel: "https://wh40k.lexicanum.com/wiki/Somnus_Citadel",
    lexicanumSelenar: "https://wh40k.lexicanum.com/wiki/Selenar",
    nasaMoonKit: "https://svs.gsfc.nasa.gov/4720/",
    wikiAlamutCastle: "https://en.wikipedia.org/wiki/Alamut_Castle"
  },
  layers: [
    { id: "palace", name: "Imperial Palace", icon: "fort", color: "#b5f3ef" },
    { id: "throne", name: "Throne Sanctums", icon: "encrypted", color: "#e06b55" },
    { id: "admin", name: "Administratum", icon: "account_balance", color: "#78c6c8" },
    { id: "faith", name: "Ecclesiarchy", icon: "church", color: "#d6c27a" },
    { id: "military", name: "Defence Grid", icon: "security", color: "#9ccfff" },
    { id: "transit", name: "Ports / Transit", icon: "rocket_launch", color: "#7dbb7e" },
    { id: "hives", name: "Terran Hives", icon: "domain", color: "#9e8fd6" },
    { id: "orbital", name: "Orbital", icon: "orbit", color: "#cfd8dc" }
  ],
  patterns: [
    { id: "himalazia-palace-zone", layer: "palace", name: "Himalazia Palace Shield", latMin: 20, latMax: 40, lonMin: 260, lonMax: 290, pattern: "target" },
    { id: "astronomican-conduits", layer: "throne", name: "Astronomican Conduit Range", latMin: 24, latMax: 38, lonMin: 264, lonMax: 288, pattern: "circuit" },
    { id: "senatorum-bureaucracy", layer: "admin", name: "Senatorum Data Web", latMin: 18, latMax: 42, lonMin: 255, lonMax: 295, pattern: "data" },
    { id: "terra-pilgrim-hives", layer: "hives", name: "Pilgrim Hive Sprawl", latMin: -12, latMax: 58, lonMin: 295, lonMax: 40, pattern: "hex" },
    { id: "terran-defence-ring", layer: "military", name: "Palace Defence Net", latMin: 5, latMax: 48, lonMin: 244, lonMax: 312, pattern: "target" },
    {
      id: "orbital-plates",
      layer: "orbital",
      name: "Orbital Defence Lanes",
      latMin: -3,
      latMax: 3,
      lonMin: 0,
      lonMax: 360,
      pattern: "orbital",
      ringVisible: false,
      panelWidth: 8,
      panelMaxWidth: 12,
      panelSize: 0.022,
      panelOpacity: 0.26,
      panelColor: "#9ba4aa",
      panelWireOpacity: 0.0,
      panelStep: 1.25,
      panelRowStep: 1.1,
      panelGapChance: 0.23,
      panelHoleChance: 0.16,
      panelArcs: [{ start: 208, end: 336 }, { start: 18, end: 94 }]
    }
  ],
  traffic: {
    enabled: true,
    color: "#ffd36a",
    intensity: 1.55,
    opacity: 0.9,
    speed: 0.115,
    pause: 1.2,
    trailLength: 0.12,
    fadeDistance: 0.11,
    headPower: 2.8,
    radiusScale: 1.12,
    arcHeight: 0.34,
    lineSpacing: 0.014,
    randomness: 1,
    lateralJitter: 0.006,
    altitudeJitter: 0.018,
    arcHeightJitter: 0.05,
    tiltJitter: 0.055,
    phaseJitter: 0.22,
    speedJitter: 0.08,
    lineStagger: 0.065,
    routeStagger: 1.6,
    segments: 112
  },
  trafficRoutes: [
    { id: "palace-wyverin-convoy", from: "lions-gate-spaceport", to: "wyverin-space-port", count: 6, speed: 0.12, trailLength: 0.2, arcHeight: 0.3 },
    { id: "navis-palace-convoy", from: "navigator-quarter", to: "lions-gate-spaceport", count: 5, speed: 0.105, trailLength: 0.24, arcHeight: 0.36 },
    { id: "plate-mariana-patrol", from: "orbital-plate-network", to: "mariana-gorge", count: 4, speed: 0.14, trailLength: 0.18, arcHeight: 0.28 },
    { id: "phalanx-himalazia-watch", from: "phalanx-anchor", to: "imperial-palace", count: 8, speed: 0.095, trailLength: 0.26, arcHeight: 0.42, intensity: 1.75 },
    { id: "alamut-judgement-shadow", from: "assassinorum-temple-alamut", to: "hall-of-judgement", count: 4, speed: 0.13, trailLength: 0.16, arcHeight: 0.22, opacity: 0.7 }
  ],
  structures: [
    {
      id: "astronomican-tower",
      type: "pyramid",
      name: "Astronomican Fallback Beacon",
      lat: 39.3949,
      lon: 277.560,
      baseRadius: 0.022,
      height: 0.48,
      surfaceScale: 1.006,
      color: "#f4d27a",
      emissive: "#b56b18",
      lightColor: "#ffd36a",
      lightIntensity: 3.4,
      lightDistance: 1.25,
      glowSize: 0.34,
      glowOpacity: 0.86,
      pulseSpeed: 0.5,
      pulseIntensity: 1.35
    }
  ],
  moon: {
    title: "Luna Cogitator",
    subtitle: "Terran Orbit",
    textures: {
      colorMap: "images/moon_color_lroc_4k.jpg",
      nightMap: "images/moon_nightmap_4k.jpg",
      bumpMap: "images/moon_bump_lola_4k.jpg",
      normalMap: {
        ktx2: "images/moon_normal_lola_4k_uastc.ktx2",
        webp: "images/moon_normal_lola_4k.webp",
        fallback: "images/moon_normal_lola_4k.png"
      }
    },
    material: {
      ambientLight: 0x07080b,
      sunColor: 0xd9e6ff,
      sunIntensity: 1,
      sunPosition: { x: 13.8, y: -1.1, z: 10.95 },
      ambient: 0x7a7d86,
      emissive: 0x050505,
      specular: 0x141a22,
      shininess: 3,
      reliefMap: "bump",
      bumpScale: 0.04,
      normalScale: 12,
      mapContrast: 1,
      mapBrightness: -8,
      nightOverlay: { mode: "full", opacity: 10, radiusScale: 1.003 },
      nightGlow: { enabled: true, mode: "full", opacity: 10, threshold: 0.08, softness: 0.7, colorBoost: 0.5, radiusScale: 1.005 },
      bloom: { enabled: true, strength: 0.25, radius: 0.52, threshold: 0.28 },
      haloColor: 0x9fc7ff,
      haloOpacity: 0.06
    },
    locations: [
      {
        id: "luna-somnus-citadel",
        name: "Somnus Citadel / Silent Sisterhood Fortress",
        shortName: "Somnus Citadel",
        subtitle: "Arx Somni",
        lat: 160.5,
        lon: 28.0,
        coordinateConfidence: "campaign placement: canonical Luna site, exact selenographic coordinates not specified",
        layer: "military",
        layers: ["military", "orbital"],
        faction: "Sisters of Silence / Imperial defence command",
        status: "M42 restored fortress and Black Ship launch bastion",
        loreConfidence: "Verified: Lexicanum Luna and Somnus Citadel",
        sourceKeys: ["lexicanumLuna", "lexicanumSomnusCitadel"],
        text: "The Somnus Citadel is Luna's restored fortress of the Sisters of Silence: a Black Ship bastion, anti-psyker redoubt, and one of Guilliman's renewed seals around Terra after the Terran Crusade."
      },
      {
        id: "luna-port-luna",
        name: "Port Luna / Battlefleet Sol Shipyards",
        shortName: "Port Luna",
        subtitle: "Portus Lunae",
        lat: -3.0,
        lon: 86.0,
        coordinateConfidence: "campaign placement: naval base and orbital yard interface",
        layer: "orbital",
        layers: ["orbital", "military", "transit"],
        faction: "Battlefleet Sol / Imperialis Armada",
        status: "M41/M42 naval base, shipyard, and defence-ring anchor",
        loreConfidence: "Verified: Lexicanum Luna notable locations",
        sourceKeys: ["lexicanumLuna"],
        text: "Port Luna is the naval machine of the Throneworld's moon: Battlefleet Sol base, vast shipyard, dock lattice, and military harbour for traffic that cannot be permitted to touch Terra unexamined."
      },
      {
        id: "luna-circuit-ring",
        name: "The Circuit Ring / Valley and Defence Platform Belt",
        shortName: "Circuit Ring",
        subtitle: "Circuitus Lunae",
        lat: 2.0,
        lon: 154.0,
        coordinateConfidence: "campaign placement: combines The Circuit valley and The Ring orbital defence belt",
        layer: "orbital",
        layers: ["orbital", "military"],
        faction: "Lunar defence commands / Battlefleet Sol",
        status: "M41/M42 artificial valley, defence-belt, and orbital command zone",
        loreConfidence: "Verified as separate Luna sites: The Circuit and The Ring on Lexicanum Luna",
        sourceKeys: ["lexicanumLuna"],
        text: "The Circuit Ring merges two linked lunar defences into one cogitator marker: the artificial military valley called The Circuit below, and The Ring of lance, torpedo, and macrocannon platforms above."
      },
      {
        id: "luna-selenar-gene-labs",
        name: "Selenar Gene-Labs / Herodotus Omega Dome",
        shortName: "Herodotus Omega",
        subtitle: "Laboratoria Selenarum",
        lat: -18.0,
        lon: 238.0,
        coordinateConfidence: "campaign placement: underground gene-lab, Herodotus Omega Dome, and vault zone",
        layer: "admin",
        faction: "Selenar gene-cults / sealed Imperial genetors",
        status: "Heresy-era strategic gene-tech site, modern status restricted",
        loreConfidence: "Verified: Lexicanum Luna and Selenar",
        sourceKeys: ["lexicanumLuna", "lexicanumSelenar"],
        classified: true,
        text: "The Selenar gene-labs and ruined Herodotus Omega Dome mark Luna's buried gene-cult inheritance: Astartes production secrets, the Magna Mater vault, and biological lineages contested during the Solar War."
      }
    ]
  },
  hungarianTextById: {
    "imperial-palace": "A Császári Palota nem épület, hanem kontinensnyi erőd-hive a Himalázia hegyláncain. A Sanctum Imperialis, a zarándoklat és a végső védelem egyetlen túlterhelt birodalmi gépezetté sűrűsödik benne.",
    "golden-throne": "Az Arany Trón Terra legszentebb és legtiltottabb gép-szentélye. Az Emperor testét tartja életben, a Webway-kaput zárva tartja, és minden megközelítése pecsétek, őrségek és halálos jogosultsági próbák sora.",
    "astronomican": "Az Astronomican az Imperium pszichikus világítótornya. A Kiválasztottak élete a kamráiban ég el, hogy a Navigátorok a warpban is megtalálják Terra irányát.",
    "forbidden-fortress": "A Tiltott Erőd, más néven Hollow Mountain, az Adeptus Astronomica himaláziai szíve. Kívül hegy és zárvány; belül kamrák, gépek, áldozatok és a csillagközi jeladó szent üzeme.",
    "lions-gate-spaceport": "A Lion's Gate Spaceport a Palota nagy közlekedési ütőere. Felszíni, légköri és orbitális forgalma békében zarándok- és hadianyagáram, ostrom idején pedig kapu, erőd és csatatér.",
    "eternity-gate": "Az Eternity Gate a Belső Palota egyik végső küszöbe. A zarándoklat, az ostrom és a dogma itt egyetlen védett pontba szűkül a Sanctum Imperialis előtt.",
    "senatorum-imperialis": "A Senatorum Imperialis a High Lords politikai gépháza. Ami itt határozatként megszületik, az a galaxis peremén tized, keresztes hadjárat, tisztogatás vagy halálos ítélet lesz.",
    "adeptus-custodes-bastion": "A Custodes-bástya nem közönséges kaszárnya, hanem az Emperor személyes őrségének egyik felügyeleti pontja. Minden protokollja egyetlen feladatra épül: a Trón és a Palota végső védelmére.",
    "adeptus-administratum": "Az Administratum csarnokai a birodalom papírral, pecséttel és adatkoporsókkal működő idegrendszere. Egy elveszett akta itt éhínséget, késő regimentet vagy egy világ lassú eltűnését okozhatja.",
    "ecclesiarchal-palace": "Ez a terrani Ministorum-negyed a hit, hivatal és látványosság nyomását jelöli. Zarándokok, gyóntatók, ereklyeügyek, szent jogi viták és politikai prédikációk torlódnak egymásra.",
    "petitioner-city": "A Petitioner's City a Palota árnyékában növő várakozás-város. Családok nemzedékei élhetnek és halhatnak meg, miközben egy pecsétre, kihallgatásra, feloldozásra vagy elutasításra várnak.",
    "merica-hive-belt": "Merica ősi neve birodalmi torzulásban maradt fenn. Hive-övei embereket, kérelmeket, zarándoktesteket és ipari igényeket öntenek a Trónvilág központja felé.",
    "europa-cardinal-bastions": "Europa régi kontinensneve ma shrine-hive-ok, nemesi hivatalok és ministorumi erőd-negyedek alatt él tovább. Ez a régió Terra rituális gazdaságának fegyelmezett, túlzsúfolt szolgálója.",
    "fortress-inquisition": "A déli sarki jég alatt fekvő Inkvizíciós Erőd nem város, hanem föld alatti ítélet. Null-mezők, pszíker-csendesítők, foglyok és évente váltott Castellanok tartják zárva.",
    "navigator-quarter": "Az Oz-Tralla szigetkontinensen jelölt Navigátor-negyed a Navis Nobilite zárt nemesi enklávéja. Mutáns dinasztiák, házassági szerződések, génkönyvek és warp-útvonal titkok tartják életben.",
    "skhallax-city": "Skhallax City kampányhelyszín a régi Afrik ásványöveihez kötve. Mélyliftek, tizedkohók és shrine-foundry-k alakítják az eltemetett ércet Palota-ellátássá.",
    "hall-of-judgement": "A Hall of Judgement az Adeptus Arbites terrani ítélőszíve. Neork rom-neve alatt ősi elfogatóparancsok, bizonyíték-kripták és városokra is kiterjedő ítéletek futnak össze.",
    "assassinorum-temple-alamut": "Az Assassinorum Templom Alamut fedőnéven jelölt titkos terrani parancsközpont. A valódi helye hivatalosan ismeretlen; a perzsa erőd romjai alatt csak árnyék-irodák, halálparancsok és hamis térképek válaszolnak.",
    "white-mountain-prison": "White Mountain kampány-black-site a déli sarki Inkvizíciós rendszerben. Olyan foglyoknak épült, akiket túl hasznos kivégezni, túl veszélyes bemutatni, és túl kényes elismerni.",
    "wyverin-space-port": "Wyverin Space Port kampánybeli északi sarki void-kapu. Hideg indítóaknái, liftállványai és védelmi sínrendszerei a Palota fő útvonalait elkerülő, őrzött indulásokat kezelik.",
    "mariana-gorge": "A Mariana Gorge a régi Mariana-árok kampánybeli, kiszáradt terrani sebhelye. Mélységi zárak, örökségi szakadékok és katonai átjárók húzódnak az eltűnt óceán helyén.",
    "phalanx-anchor": "A Phalanx orbitális jelölése nem felszíni város, hanem figyelmeztetés: Terra egén mozgó erőd, Imperial Fists-eskü és void-bástya is őrködik.",
    "orbital-plate-network": "Az orbitális védelmi plate-háló Terra körül feszülő páncél. Régi orbitális városok, dokkok, ágyúk, forgalmi pontok és kivégzőplatformok tartják zárva a Trónvilág egét.",
    "luna-somnus-citadel": "A Somnus Citadel Luna csendes erőd-szíve: a Sisters of Silence visszaállított bástyája, Black Ship indítóhely, anti-pszíker erődítmény és Terra újraerősített védelmi pecsétje.",
    "luna-port-luna": "Port Luna a Trónvilág holdjának hadikikötője: Battlefleet Sol-bázis, hajógyár, dokkháló és ellenőrző kapu mindannak, ami Terrához túl közel kerülne.",
    "luna-circuit-ring": "A Circuit Ring egyetlen hadtérképi jelbe vonja össze a Circuit mesterséges katonai holdvölgyét és a Ring orbitális fegyverplatformjait. Lent sebhely, fent makroágyús korona.",
    "luna-selenar-gene-labs": "A Selenar génlaborok és a romos Herodotus Omega Dome a Hold alatti örökség sötét magjai. Astartes-titkok, Magna Mater-vaultok és tiltott vérvonalak miatt haltak meg értük birodalmak."
  },
  etymologyById: {
    "imperial-palace": "HU: Palota, de bolygóméretű erőd és civilizációs mag. EN: not a residence, a fortified throneworld core. LAT: Palatium Imperiale.",
    "golden-throne": "HU: Az arany szent rangot, a trón hatalmat és életfenntartó gépet jelöl. EN: throne as reliquary, prison, beacon-anchor, and machine. LAT: Thronus Aureus.",
    "astronomican": "HU: Csillagászati jeladó, de pszichikus értelemben. EN: the beacon used by Navigators, not a mundane lighthouse. LAT: Pharus Astronomica.",
    "forbidden-fortress": "HU: Tiltott erőd és Hollow Mountain: a hegy fedőnév, zár és géptest egyszerre. EN: mountain as fortress for the Astronomican. LAT: Arx Vetita.",
    "lions-gate-spaceport": "HU: Oroszlánkapu: védelmi és közlekedési név egyszerre. EN: gate, fortress, and port combined. LAT: Porta Leonis.",
    "eternity-gate": "HU: Örökkévalóság kapuja, a szent belső tér küszöbe. EN: a final Palace threshold. LAT: Porta Aeternitatis.",
    "senatorum-imperialis": "HU: Birodalmi tanács, de valójában kormányzati hadigép. EN: the High Lords' chamber as state engine. LAT: Senatorum Imperialis.",
    "adeptus-custodes-bastion": "HU: Aurum Custodia: arany őrség, a Custodes színéhez és feladatához kötve. EN: golden guard precinct. LAT: Aurum Custodia.",
    "adeptus-administratum": "HU: Archivum Terrae: Terra levéltára, ahol az irat sorssá válik. EN: archive as planetary nervous system. LAT: Archivum Terrae.",
    "ecclesiarchal-palace": "HU: Domus Ministorum: a Ministorum háza, nem feltétlen egyetlen palota. EN: Terran shrine-office precinct. LAT: Domus Ministorum.",
    "petitioner-city": "HU: Kérvényezők városa. EN: a settlement defined by waiting for Imperial judgement. LAT: Civitas Supplicantium.",
    "merica-hive-belt": "HU: Merica az ősi Amerika birodalmi torzulása. EN: ancient name preserved as hive-region. LAT: Civitates Mericae.",
    "europa-cardinal-bastions": "HU: Europa régi kontinensnév, itt cardinalis/shrine-hive súllyal. EN: old Europe recast as devotional bastion. LAT: Bastiones Europae.",
    "fortress-inquisition": "HU: A déli sarki jég alatti Inkvizíciós központ. EN: polar ice as seal, prison, and interrogation machine. LAT: Arx Inquisitionis Australis.",
    "navigator-quarter": "HU: Oz-Tralla a régi Australia torzult neve. EN: island-continent quarter for warp-sighted houses. LAT: Quartus Navigatorum.",
    "skhallax-city": "HU: Kampányhelyszín Afrik bányászati övében. EN: mineral wealth converted into hive obligation. LAT: Civitas Metallorum Skhallax.",
    "hall-of-judgement": "HU: Neork a régi New York torzult neve. EN: Imperial law turned into fortress and archive. LAT: Aula Judicii.",
    "assassinorum-temple-alamut": "HU: Alamut a történelmi Asszaszinok híres hegyi erődje; itt a név fedőpecsét és félrevezetés. EN: Eagle's Nest recast as a hidden Temple of Assassins. LAT: Templum Sicariorum Alamut.",
    "white-mountain-prison": "HU: Fehér hegy, fekete nyilvántartás. EN: a prison named like geography but filed like erasure. LAT: Mons Albus Carcer.",
    "wyverin-space-port": "HU: Wyverin néven jelölt poláris void-kapu. EN: campaign polar launch port for guarded departures. LAT: Portus Wyverin.",
    "mariana-gorge": "HU: Mariana Gorge a régi Mariana-árok kiszáradt emléke. EN: oceanic scar preserved as dry abyss. LAT: Fossa Mariana.",
    "phalanx-anchor": "HU: Praesidium Phalanx: a Phalanx mint védelmi jelenlét, nem felszíni város. EN: orbital bastion marker. LAT: Praesidium Phalanx.",
    "orbital-plate-network": "HU: Corona Defensionis Terrae: Terra körüli védelmi korona. EN: dock, gun, shield, and traffic shell. LAT: Corona Defensionis Terrae.",
    "luna-somnus-citadel": "HU: Somnus az alvás, csend és lezárás neve. EN: a silent fortress for the Silent Sisterhood. LAT: Arx Somni.",
    "luna-port-luna": "HU: Luna kikötője, Terra legközelebbi hadikapuja. EN: naval station and shipyard-moon in one name. LAT: Portus Lunae.",
    "luna-circuit-ring": "HU: Circuit és Ring két külön holdi név, itt stratégiai összevont jelölés. EN: valley-circuit below, defence-ring above. LAT: Circuitus Lunae.",
    "luna-selenar-gene-labs": "HU: Selenar a holdi génkultok neve; Herodotus Omega a zárt dóm/vault jelölés. EN: creation laboratories below the old moon. LAT: Laboratoria Selenarum."
  },
  notableById: {
    "imperial-palace": [{ name: "The Emperor of Mankind", role: "enthroned sovereign and sacred centre of Terra" }, { name: "Adeptus Custodes", role: "primary guardians of the Palace and Sanctum Imperialis" }],
    "golden-throne": [{ name: "The Emperor of Mankind", role: "kept alive upon the Throne and bound to Terra's survival" }, { name: "Adeptus Mechanicus throne adepts", role: "maintenance rites, life-support burdens, and failing sacred machinery" }],
    "astronomican": [{ name: "Adeptus Astronomica", role: "institution responsible for the psychic beacon and its sacrifices" }, { name: "Master of the Astronomican", role: "High Lord office overseeing the beacon's operation" }],
    "forbidden-fortress": [{ name: "Adeptus Astronomica", role: "masters of the Hollow Mountain complex" }, { name: "The Chosen", role: "psykers consumed in the beacon's operation" }],
    "lions-gate-spaceport": [{ name: "Palace defence command", role: "spaceport security and siege-time traffic control" }, { name: "Imperial Army and void-lift crews", role: "movement of personnel, materiel, and orbital cargo" }],
    "eternity-gate": [{ name: "Sanguinius", role: "Heresy-era defender remembered at the gate" }, { name: "Adeptus Custodes", role: "guardians of the inner Palace threshold" }],
    "senatorum-imperialis": [{ name: "High Lords of Terra", role: "ruling council of the Imperium" }, { name: "Roboute Guilliman", role: "Imperial Regent whose return reshaped Terran politics" }],
    "adeptus-custodes-bastion": [{ name: "Captain-General Trajann Valoris", role: "modern commander of the Adeptus Custodes" }, { name: "Companions", role: "Custodes assigned closest to the Emperor's presence" }],
    "adeptus-administratum": [{ name: "Adeptus Administratum", role: "bureaucratic engine of Imperial tithe, census, and decree" }, { name: "Master of the Administratum", role: "High Lord office tied to Imperial bureaucracy" }],
    "ecclesiarchal-palace": [{ name: "Adeptus Ministorum", role: "Imperial Cult authority and shrine administration" }, { name: "Ecclesiarch", role: "High Lord and supreme priest of the Imperial Creed" }],
    "petitioner-city": [{ name: "Adeptus Terra clerks", role: "petition routing, audience control, and stamp authority" }, { name: "Pilgrim families", role: "multi-generation seekers of judgement and access" }],
    "merica-hive-belt": [{ name: "Terran hive prefectures", role: "regional tithe, labour, and civil control" }, { name: "Munitorum levy factors", role: "manpower extraction and supply accounting" }],
    "europa-cardinal-bastions": [{ name: "Adeptus Ministorum cardinals", role: "regional shrine and doctrine authority" }, { name: "Local hive prefectures", role: "hab order, pilgrim control, and tithe enforcement" }],
    "fortress-inquisition": [{ name: "The Castellan", role: "annually rotating overseer of the polar fortress" }, { name: "Ordo conclaves", role: "sealed cells, null fields, interrogation, and prisoner handling" }],
    "navigator-quarter": [{ name: "Navis Nobilite houses", role: "Navigator dynasties and warp-route custodians" }, { name: "Paternova's agents", role: "noble-house influence, breeding politics, and Terran representation" }],
    "skhallax-city": [{ name: "Terran hive-mining combines", role: "campaign extraction authority and labour control" }, { name: "Munitorum tithe factors", role: "ore quotas, furnace output, and military allocation" }],
    "hall-of-judgement": [{ name: "Grand Provost Marshal", role: "High Lord office and leader of the Adeptus Arbites, seated from the Hall of Judgement" }, { name: "Adeptus Arbites", role: "Imperial law enforcement, warrants, evidence crypts, and planetary-scale precedent" }],
    "assassinorum-temple-alamut": [{ name: "Grand Master of Assassins", role: "secretive head of the Officio Assassinorum and holder of Senatorum-level authority" }, { name: "Lord Assassins", role: "temple masters who train, plan, and direct Imperial assassins from hidden Terran cells" }],
    "white-mountain-prison": [{ name: "Inquisitorial gaol-wardens", role: "black-site custody and memory-sealed transfer" }, { name: "Null cadre", role: "anti-psyker containment and silence protocols" }],
    "wyverin-space-port": [{ name: "Imperial Navy traffic officers", role: "campaign polar launch scheduling and void clearance" }, { name: "Palace customs provosts", role: "sealed cargo inspection and pilgrim-route interdiction" }],
    "mariana-gorge": [{ name: "Terran heritage wardens", role: "campaign guardians of the abyssal scar and sealed galleries" }, { name: "Depth-fortress commanders", role: "military control of gorge approaches" }],
    "phalanx-anchor": [{ name: "Imperial Fists", role: "Chapter bound to Terra's defence traditions" }, { name: "Phalanx", role: "mobile fortress-monastery and void bastion" }],
    "orbital-plate-network": [{ name: "Battlefleet Solar", role: "void defence, traffic interdiction, and orbital command" }, { name: "Palace defence platforms", role: "guns, shields, docks, and execution authority above Terra" }],
    "luna-somnus-citadel": [{ name: "Sisters of Silence", role: "restored garrison and anti-psyker authority" }, { name: "Roboute Guilliman", role: "restorer of the Citadel after the Terran Crusade" }],
    "luna-port-luna": [{ name: "Battlefleet Sol", role: "naval defence and shipyard command" }, { name: "Port Luna voidmasters", role: "dock, yard, and defence-ring traffic authority" }],
    "luna-circuit-ring": [{ name: "Lunar defence commands", role: "coordination of The Circuit and The Ring" }, { name: "Battlefleet Sol sentry crews", role: "lance, torpedo, and macrocannon platform watch" }],
    "luna-selenar-gene-labs": [{ name: "Selenar gene-cults", role: "ancient lunar gene-tech custodians" }, { name: "Ta'lab Vita-37", role: "Selenar matriarch tied to the Magna Mater legacy" }]
  },
  locations: [
    {
      id: "imperial-palace",
      name: "Imperial Palace / Himalazia Macro-Fortress",
      shortName: "Imperial Palace",
      subtitle: "Palatium Imperiale",
      lat: 33.8,
      lon: 268.1,
      coordinateConfidence: "approximate: Himalazia palace zone",
      layer: "palace",
      layers: ["palace", "military"],
      faction: "Adeptus Terra / Imperial Household",
      status: "M41/M42 active throneworld command core",
      loreConfidence: "Verified: Lexicanum Terra, Imperial Palace",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "The Imperial Palace is not a residence but a continent-scale fortress-hive across the Himalazia. It houses the Sanctum Imperialis, the Adeptus Terra's central machinery, and the Imperium's final defensive heart."
    },
    {
      id: "golden-throne",
      name: "Golden Throne / Sanctum Imperialis",
      shortName: "Golden Throne",
      subtitle: "Thronus Aureus",
      lat: 29.00,
      lon: 273.03,
      coordinateConfidence: "classified: Palace interior approximation",
      layer: "throne",
      layers: ["throne", "palace"],
      faction: "Adeptus Custodes / Mechanicus throne adepts",
      status: "M41/M42 active and failing sacred machine",
      loreConfidence: "Verified: Lexicanum Golden Throne, Terra",
      sourceKeys: ["lexicanumGoldenThrone", "lexicanumTerra"],
      classified: true,
      text: "The Golden Throne sustains the Emperor's body, seals the failed Webway gate, and anchors the Astronomican's direction. Access to it is a chain of wards, Custodes authority, Mechanicus rites, and lethal exclusion."
    },
    {
      id: "astronomican",
      name: "Astronomican Beacon Complex",
      shortName: "Astronomican",
      subtitle: "Pharus Astronomica",
      lat: 38.2,
      lon: 277.5,
      coordinateConfidence: "approximate: Himalazia beacon complex",
      layer: "throne",
      layers: ["throne", "orbital"],
      faction: "Adeptus Astronomica",
      status: "M41/M42 active psychic navigation beacon",
      loreConfidence: "Verified: Lexicanum Astronomican, Forbidden Fortress",
      sourceKeys: ["lexicanumAstronomican", "lexicanumForbiddenFortress"],
      text: "The Astronomican is the psychic beacon Navigators use to cross the warp. Its Chosen burn out in the Chamber of the Astronomican while the Emperor's will directs their light across the Imperium."
    },
    {
      id: "forbidden-fortress",
      name: "Forbidden Fortress / Hollow Mountain",
      shortName: "Hollow Mountain",
      subtitle: "Fortress of the Astronomican",
      lat: 34.6,
      lon: 281.2,
      coordinateConfidence: "approximate: remote Himalazia complex",
      layer: "throne",
      layers: ["throne", "palace"],
      faction: "Adeptus Astronomica",
      status: "M41/M42 restricted beacon fortress",
      loreConfidence: "Verified: Lexicanum Forbidden Fortress",
      sourceKeys: ["lexicanumForbiddenFortress"],
      classified: true,
      text: "The Forbidden Fortress, or Hollow Mountain, is the Himalazian fortress of the Adeptus Astronomica. Its carved peak and sealed depths house the machinery, chambers, and sacrifice that feed the beacon."
    },
    {
      id: "lions-gate-spaceport",
      name: "Lion's Gate Spaceport",
      shortName: "Lion's Gate",
      subtitle: "Porta Leonis",
      lat: 40.95,
      lon: 258.55,
      coordinateConfidence: "approximate: Palace outer/inner gate interface",
      layer: "transit",
      layers: ["transit", "military"],
      faction: "Imperial Palace traffic authority",
      status: "M41/M42 active major spaceport",
      loreConfidence: "Verified: Lexicanum Lion's Gate Spaceport",
      sourceKeys: ["lexicanumLionsGate", "lexicanumPalace"],
      text: "Lion's Gate Spaceport is the Palace's great transport artery, linking surface precincts, high atmosphere, and orbital traffic. In war it becomes gate, fortress, and battlefield at once."
    },
    {
      id: "eternity-gate",
      name: "Eternity Gate",
      shortName: "Eternity Gate",
      subtitle: "Porta Aeternitatis",
      lat: 27.25,
      lon: 273.15,
      coordinateConfidence: "approximate: Palace inner sanctum gate",
      layer: "palace",
      layers: ["palace", "military", "throne"],
      faction: "Adeptus Custodes",
      status: "M41/M42 active sacred gate",
      loreConfidence: "Referenced in Terra and Palace siege records",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "The Eternity Gate is the great threshold of the Inner Palace and the end point of countless pilgrim dreams. In siege records it is not only a door, but the line before the Sanctum Imperialis."
    },
    {
      id: "senatorum-imperialis",
      name: "Great Chamber of the Senatorum Imperialis",
      shortName: "Senatorum",
      subtitle: "High Lords' Chamber",
      lat: 31.2,
      lon: 280.28,
      coordinateConfidence: "approximate: Imperial Palace governance district",
      layer: "admin",
      layers: ["admin", "palace"],
      faction: "High Lords of Terra",
      status: "M41/M42 active Imperial ruling chamber",
      loreConfidence: "Verified: Lexicanum Senatorum Imperialis",
      sourceKeys: ["lexicanumSenatorum", "lexicanumTerra"],
      text: "The Great Chamber of the Senatorum Imperialis is where the High Lords turn crisis into edict. Its votes become tithes, crusades, purges, pardons, and death warrants across human space."
    },
    {
      id: "adeptus-custodes-bastion",
      name: "Adeptus Custodes Palace Bastion",
      shortName: "Custodes Bastion",
      subtitle: "Aurum Custodia",
      lat: 31.32,
      lon: 268.0,
      coordinateConfidence: "approximate: Palace defence district",
      layer: "military",
      layers: ["military", "palace"],
      faction: "Adeptus Custodes",
      status: "M41/M42 active elite defence node",
      loreConfidence: "Verified: Lexicanum Adeptus Custodes, Terra",
      sourceKeys: ["lexicanumCustodes", "lexicanumTerra"],
      text: "This bastion represents the Custodes watch over the Palace, from outer walls to hidden cells. Its protocols are older than most Imperial institutions and exist for one duty: the Emperor's defence."
    },
    {
      id: "adeptus-administratum",
      name: "Adeptus Administratum Record Halls",
      shortName: "Administratum",
      subtitle: "Archivum Terrae",
      lat: -24,
      lon: 130.1,
      coordinateConfidence: "approximate: Palace bureaucratic sprawl",
      layer: "admin",
      layers: ["admin", "hives"],
      faction: "Adeptus Administratum",
      status: "M41/M42 active Imperial bureaucracy",
      loreConfidence: "Verified headquarters context: Lexicanum Terra",
      sourceKeys: ["lexicanumTerra", "lexicanumSenatorum"],
      text: "The Administratum record halls are Terra's bureaucratic nervous system. Petitions, tithes, census rolls, war demands, and contradictory decrees pass through archives large enough to bury worlds in delay."
    },
    {
      id: "ecclesiarchal-palace",
      name: "Ecclesiarchal Palace / Terran Synod Precinct",
      shortName: "Ecclesiarchy",
      subtitle: "Domus Ministorum",
      lat: 41.9,
      lon: 347.5,
      coordinateConfidence: "symbolic approximation: ancient Roma precinct",
      layer: "faith",
      layers: ["faith", "admin"],
      faction: "Adeptus Ministorum",
      status: "M41/M42 active religious power node",
      loreConfidence: "Institution verified: Terra and Senatorum context",
      sourceKeys: ["lexicanumTerra", "lexicanumSenatorum"],
      text: "This Terran synod precinct marks the Ministorum's shrine and court presence on Holy Terra. Faith here is administration as much as worship: sermons, indulgences, relic claims, pilgrim law, and political pressure."
    },
    {
      id: "petitioner-city",
      name: "Petitioner City",
      shortName: "Petitioner City",
      subtitle: "Civitas Supplicantium",
      lat: 17.8,
      lon: 280.2,
      coordinateConfidence: "approximate: Palace-adjacent pilgrim sprawl",
      layer: "hives",
      faction: "Pilgrims / Adeptus Terra clerks",
      status: "M41/M42 active waiting-city",
      loreConfidence: "Terra pilgrim context, cartographic approximation",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "Petitioner's City is the waiting-sprawl at the edge of Imperial authority. Families can spend generations pursuing a stamp, audience, absolution, or judgement that may never arrive."
    },
    {
      id: "merica-hive-belt",
      name: "Merica Hive Belt",
      shortName: "Merica Hives",
      subtitle: "Civitates Mericae",
      lat: 39.5,
      lon: 98.0,
      coordinateConfidence: "approximate: ancient North Merican continental zone",
      layer: "hives",
      faction: "Terran hive authorities",
      status: "M41/M42 active hive and tithe belt",
      loreConfidence: "Old Terra name verified in Lexicanum Terra",
      sourceKeys: ["lexicanumTerra"],
      text: "Merica is an ancient Terran name preserved through Imperial distortion. Its hive belts are treated here as tithe engines: manpower, petitions, pilgrim bodies, and industrial demand moving toward the Palace."
    },
    {
      id: "europa-cardinal-bastions",
      name: "Europa Cardinal Bastions",
      shortName: "Europa Bastions",
      subtitle: "Bastiones Europae",
      lat: 48.8,
      lon: 351.8,
      coordinateConfidence: "approximate: ancient Europa continental zone",
      layer: "faith",
      layers: ["faith", "hives"],
      faction: "Adeptus Ministorum / local hive prefectures",
      status: "M41/M42 active shrine-hive region",
      loreConfidence: "Old Terra name verified in Lexicanum Terra",
      sourceKeys: ["lexicanumTerra"],
      text: "Europa is an old continental name under layers of shrine-hive, hab block, and noble office. This marker frames the region as a Ministorum-heavy bastion network serving Terra's ritual economy."
    },
    {
      id: "fortress-inquisition",
      name: "Fortress of the Inquisition / South Polar Ice",
      shortName: "Inquisition Fortress",
      subtitle: "Arx Inquisitionis Australis",
      lat: -87.0,
      lon: 20.0,
      coordinateConfidence: "approximate: beneath the south polar ice caps",
      layer: "military",
      faction: "The Inquisition",
      status: "M41/M42 active subterranean headquarters and prison complex",
      loreConfidence: "Verified location: Lexicanum Terra; polar placement from Terra geography",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumInquisition"],
      classified: true,
      text: "The Fortress of the Inquisition is a vast underground complex beneath the south polar ice. Wards, null-fields, psyker-dampening engines, prisoners, and rotating Castellans make it a headquarters and a sentence."
    },
    {
      id: "navigator-quarter",
      name: "Navigator's Quarter / Oz-Tralla Island Enclave",
      shortName: "Navigator Quarter",
      subtitle: "Quartus Navigatorum",
      lat: -25.3,
      lon: 226.5,
      coordinateConfidence: "campaign placement: Oz-Tralla / ancient Australia",
      layer: "transit",
      layers: ["transit"],
      faction: "Navis Nobilite",
      status: "M41/M42 active Navigator noble enclave and sealed quarter",
      loreConfidence: "Verified location name: Lexicanum Terra; Oz-Tralla placement from Terra geography",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumNavisNobilite"],
      text: "The Navigator's Quarter is the Navis Nobilite's massive-island enclave. Manor-spires, gene-ledgers, marriage contracts, and warp-route privileges are guarded behind noble law, household troops, and sanctioned mutation."
    },
    {
      id: "skhallax-city",
      name: "Skhallax City / Afrik Mineral Hive",
      shortName: "Skhallax City",
      subtitle: "Civitas Metallorum Skhallax",
      lat: -11.7,
      lon: 332.5,
      coordinateConfidence: "campaign placement: central Afrik mineral belt",
      layer: "hives",
      faction: "Terran hive-mining combines",
      status: "M41/M42 active extraction hive",
      loreConfidence: "Campaign location grounded in Lexicanum Terra Afrik region and mineral-rich placement",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography"],
      text: "Skhallax City is a campaign hive-mining knot placed in old Afrik's resource belt. Deep elevators, tithe furnaces, and shrine-foundries turn buried ore into Palace supply and Munitorum obligation."
    },
    {
      id: "hall-of-judgement",
      name: "Hall of Judgement / Neork Arbites Seat",
      shortName: "Hall of Judgement",
      subtitle: "Aula Judicii",
      lat: 40.7,
      lon: 74.0,
      coordinateConfidence: "campaign placement: Neork / ancient New York",
      layer: "admin",
      layers: ["admin"],
      faction: "Adeptus Arbites",
      status: "M41/M42 active Arbites headquarters",
      loreConfidence: "Verified location name and Arbites role: Lexicanum Terra and Adeptus Arbites",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumArbites"],
      text: "The Hall of Judgement is the Terran seat of the Adeptus Arbites. Its precincts hold warrants older than dynasties and rulings broad enough to condemn cities, cults, noble houses, and planetary offices."
    },
    {
      id: "assassinorum-temple-alamut",
      name: "Temple of Assassins / Alamut Shadow Cell",
      shortName: "Assassinorum Temple",
      subtitle: "Templum Sicariorum Alamut",
      lat: 36.45,
      lon: 309.41,
      coordinateConfidence: "campaign placement: historical Alamut Castle anchor; canonical Temple of Assassins location remains secret",
      layer: "military",
      layers: ["military", "admin"],
      faction: "Officio Assassinorum",
      status: "M41/M42 classified assassin command and sanction cell",
      loreConfidence: "Verified: Officio Assassinorum has a secretive Temple of Assassins on Terra; Alamut placement is campaign interpretation",
      sourceKeys: ["lexicanumOfficioAssassinorum", "wikiAlamutCastle"],
      classified: true,
      traitorSensitive: true,
      text: "The Temple of Assassins is the hidden heart of the Officio Assassinorum on Terra. This Alamut marker is a campaign cover-site: an ancient mountain fortress repurposed as misdirection, sanction archive, and deployment cell for deaths that must never look like Imperial policy."
    },
    {
      id: "white-mountain-prison",
      name: "White Mountain / South Polar Secret Prison",
      shortName: "White Mountain",
      subtitle: "Mons Albus Carcer",
      lat: -84.0,
      lon: 80.0,
      coordinateConfidence: "campaign placement: south polar black-site spur",
      layer: "military",
      faction: "Inquisition / sealed gaol authority",
      status: "M41/M42 classified prison and null containment annex",
      loreConfidence: "Campaign prison tied to the canonical south-polar Inquisition fortress complex",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography", "lexicanumInquisition"],
      classified: true,
      traitorSensitive: true,
      text: "White Mountain is a campaign black-site attached to the south polar Inquisition complex: a prison-spur for prisoners too useful to execute, too dangerous to expose, and too politically charged to admit."
    },
    {
      id: "wyverin-space-port",
      name: "Wyverin Space Port / North Polar Void Gate",
      shortName: "Wyverin Port",
      subtitle: "Portus Wyverin Borealis",
      lat: 84.0,
      lon: 340.0,
      coordinateConfidence: "campaign placement: north polar launch region",
      layer: "transit",
      layers: ["transit"],
      faction: "Imperial Navy / Palace traffic commands",
      status: "M41/M42 active polar spaceport",
      loreConfidence: "Campaign spaceport placed in Terra's polar traffic network",
      sourceKeys: ["lexicanumTerra", "lexicanumTerraGeography"],
      text: "Wyverin Space Port is a campaign northern polar void-gate. Its launch caissons, cold lift gantries, and defence rails handle guarded departures that must avoid the Palace's main transit arteries."
    },
    {
      id: "mariana-gorge",
      name: "Mariana Gorge / Mariana Canyon",
      shortName: "Mariana Gorge",
      subtitle: "Fossa Mariana",
      lat: 11.35,
      lon: 217.8,
      coordinateConfidence: "approximate: ancient Mariana Trench region",
      layer: "admin",
      faction: "Terran heritage wardens / sealed depth authorities",
      status: "M41/M42 restricted abyssal heritage and defence zone",
      loreConfidence: "Verified region name: Lexicanum Terra geography",
      sourceKeys: ["lexicanumTerraGeography"],
      text: "Mariana Gorge is the campaign form of the old Mariana Trench after Terra's oceans vanished: a dry abyss, heritage wound, sealed approach, and depth-fortified military corridor."
    },
    {
      id: "phalanx-anchor",
      name: "Phalanx Strategic Anchor",
      shortName: "Phalanx Anchor",
      subtitle: "Praesidium Phalanx",
      lat: 0,
      lon: 320,
      coordinateConfidence: "orbital: representative station longitude",
      layer: "orbital",
      layers: ["orbital", "military"],
      faction: "Imperial Fists",
      status: "mobile orbital fortress, strategic Terra defence asset",
      loreConfidence: "Verified: Lexicanum Phalanx, Terra defence context",
      sourceKeys: ["lexicanumPhalanx", "lexicanumTerra"],
      text: "The Phalanx anchor is an orbital overlay for the Imperial Fists' fortress-monastery and its role in Terra's defence. It marks a mobile bastion, not a fixed city on the surface."
    },
    {
      id: "orbital-plate-network",
      name: "Terran Orbital Plate Network",
      shortName: "Orbital Plates",
      subtitle: "Corona Defensionis Terrae",
      lat: 0,
      lon: 180,
      coordinateConfidence: "orbital equatorial defence band",
      layer: "orbital",
      layers: ["orbital", "military"],
      faction: "Imperial Navy / Palace defence commands",
      status: "M41/M42 active orbital defence and traffic shell",
      loreConfidence: "Terra orbital defence context, campaign abstraction",
      sourceKeys: ["lexicanumTerra"],
      text: "The orbital plate network is a campaign abstraction for Terra's old orbital cities, defence platforms, dock structures, and traffic shell. It is armour, customs office, and execution platform above the Throneworld."
    }
  ]
};
