window.PLANET_RPG_DATA = {
  appName: "Earth Cogitator Map",
  CLASSIFIED_PASSKEY: "TERRA",
  classifiedStorageKey: "earth-classified-unlocked",
  longitudeLabels: "eastWest",
  textures: {
    dayMap: "images/earth_daymap_8k.jpg",
    nightMap: "images/earth_nightmap_8k.jpg",
    colorMap: "images/earth_daymap_8k.jpg",
    normalMap: "images/earth_normal_map_8k.png",
    specularMap: "images/earth_specular_map_8k.png",
    cloudMap: "images/earth_clouds_8k.jpg"
  },
  material: {
    // surfaceMap accepts "day", "night", or "daynight"; sunFocus lon uses the renderer's west-positive convention, so 270 = 90E.
    surfaceMap: "daynight",
    // nightOverlay.mode accepts "full" for global lights or "nightoverlap" for night-side-only lights.
    nightOverlay: { mode: "full", opacity: 0.95, edgeSoftness: 0.75, radiusScale: 1.002 },
    sunFocus: { lat: 30.0, lon: 270.0, distance: 1 },
    sunColor: 0xfff1c8,
    sunIntensity: 0.48,
    ambientLight: 0x10181a,
    ambient: 0x6f858a,
    emissive: 0x020608,
    specular: 0x476b7d,
    shininess: 22,
    normalScale: 10,
    haloColor: 0x9ccfff,
    haloOpacity: 0.07,
    cloudOpacity: 0.04
  },
  sources: {
    lexicanumTerra: "https://wh40k.lexicanum.com/wiki/Terra",
    lexicanumPalace: "https://wh40k.lexicanum.com/wiki/Imperial_Palace",
    lexicanumGoldenThrone: "https://wh40k.lexicanum.com/wiki/Golden_Throne",
    lexicanumAstronomican: "https://wh40k.lexicanum.com/wiki/Astronomican",
    lexicanumForbiddenFortress: "https://wh40k.lexicanum.com/wiki/Forbidden_Fortress",
    lexicanumLionsGate: "https://wh40k.lexicanum.com/wiki/Lion%27s_Gate_Spaceport",
    lexicanumSenatorum: "https://wh40k.lexicanum.com/wiki/High_Lords_of_Terra",
    lexicanumCustodes: "https://wh40k.lexicanum.com/wiki/Adeptus_Custodes",
    lexicanumPhalanx: "https://wh40k.lexicanum.com/wiki/Phalanx"
  },
  layers: [
    { id: "palace", name: "Imperial Palace", icon: "fort", color: "#b5f3ef" },
    { id: "throne", name: "Throne Sanctums", icon: "encrypted", color: "#e06b55" },
    { id: "admin", name: "Administratum", icon: "account_balance", color: "#78c6c8" },
    { id: "faith", name: "Ecclesiarchy", icon: "church", color: "#d6c27a" },
    { id: "military", name: "Defence Grid", icon: "security", color: "#9ccfff" },
    { id: "transit", name: "Ports / Transit", icon: "rocket_launch", color: "#7dbb7e" },
    { id: "hives", name: "Terran Hives", icon: "domain", color: "#9e8fd6" },
    { id: "orbital", name: "Orbital", icon: "orbit", color: "#cfd8dc" }
  ],
  patterns: [
    { id: "himalazia-palace-zone", layer: "palace", name: "Himalazia Palace Shield", latMin: 20, latMax: 40, lonMin: 260, lonMax: 290, pattern: "target" },
    { id: "astronomican-conduits", layer: "throne", name: "Astronomican Conduit Range", latMin: 24, latMax: 38, lonMin: 264, lonMax: 288, pattern: "circuit" },
    { id: "senatorum-bureaucracy", layer: "admin", name: "Senatorum Data Web", latMin: 18, latMax: 42, lonMin: 255, lonMax: 295, pattern: "data" },
    { id: "terra-pilgrim-hives", layer: "hives", name: "Pilgrim Hive Sprawl", latMin: -12, latMax: 58, lonMin: 295, lonMax: 40, pattern: "hex" },
    { id: "terran-defence-ring", layer: "military", name: "Palace Defence Net", latMin: 5, latMax: 48, lonMin: 244, lonMax: 312, pattern: "target" },
    { id: "orbital-plates", layer: "orbital", name: "Orbital Defence Lanes", latMin: -3, latMax: 3, lonMin: 0, lonMax: 360, pattern: "orbital" }
  ],
  hungarianTextById: {
    "imperial-palace": "A Csaszari Palota nem egy epulet, hanem kontinensnyi erod-varos a Himalazia hegylancaiban. A birodalmi hatalom, a zarandoklat es a vegso vedelmi vonal egyetlen tulterhelt gepezete.",
    "golden-throne": "Az Arany Tronus a Terra legszentebb es legtiltottabb magja. A hozza vezeto utak nem utvonalak, hanem jogosultsagi probak, pecsetek es halalos orsegek sorozata.",
    "astronomican": "Az Astronomican fenyjele a birodalom csillagkozi iranytuje. A helyszin korul a hit, a pszichikus aldozat es az osregi technologia egyetlen ritualis uzemmel olvad ossze.",
    "forbidden-fortress": "A Tiltott Erod, mas neven Hollow Mountain, az Adeptus Astronomica titkos Himalazia-komplexuma. Kivulrol hegy, belulrol szent gepezet es lezaras.",
    "lions-gate-spaceport": "A Lion's Gate Spaceport a Palota legnagyobb kozlekedesi csomopontja. Felszini, legkori es orbitalis forgalma a Tronvilag veraramakent mukodik.",
    "eternity-gate": "Az Eternity Gate a belso szentelyek egyik vegso kapuja. Neve onmagaban hadparancs: itt a zarandoklat, az ostrom es a dogma egy pontba szukul.",
    "senatorum-imperialis": "A Senatorum Imperialis a High Lords politikai szive. A dontesek innen indulnak, de mire a galaxis peremere ernek, mar rendeletek, adok es hadparancsok hegyeve valnak.",
    "adeptus-custodes-bastion": "A Custodes bastion nem egyszeru kaszarnya, hanem az Emperor szemelyes orsegenek felugyeleti pontja. Minden protokollja a vegso vedelmet szolgalja.",
    "adeptus-administratum": "Az Administratum csarnokai a birodalom papiralapu idegrendszere. Ami itt elveszik, az egesz vilagok sorsat torolheti ki.",
    "ecclesiarchal-palace": "Az Ecclesiarchal Palace a hit politikai es ritualis tulnyomasa. Zarandokok, predikatorok es szent hivatalok torlodnak egymasra.",
    "petitioner-city": "A Petitioner City a Palota arnyekaban novekvo varakozas-varos. Generaciok elnek es halnak meg, mikozben egy engedelyre, iteletere vagy alairasra varnak.",
    "merica-hive-belt": "Merica regi neve mar csak birodalmi torzulasban el. Hive-ovei adokat, katonakat es zarandokokat ontanak a Tronvilag kozepe fele.",
    "europa-cardinal-bastions": "Europa regi kontinense ma szent hivatalok, cardinialis bastionok es fegyelmezett hive-negyedek osszenott tomege.",
    "phalanx-anchor": "A Phalanx orbitalis jelenlete nem varos, hanem figyelmeztetes: a Terra folotti eg nem ures, hanem fegyverrel es eskukkel kitoltott ter.",
    "orbital-plate-network": "Az orbitalis vedelmi plate-halo a vilag korul feszulo pancel. Dokkok, agyuk, void-pajzsok es forgalmi pontok tartjak zarva a Tronvilag egeit."
  },
  etymologyById: {
    "imperial-palace": "HU: Palota, de bolygomeretu erod. EN: not a residence, a fortified civilization core. LAT: Palatium Imperiale.",
    "golden-throne": "HU: Arany a szent rang; Tronus a hatalom es eletben tartas helye. EN: throne as reliquary and machine. LAT: Thronus Aureus.",
    "astronomican": "HU: Csillagaszati jelado neve. EN: the psychic lighthouse of Imperial navigation. LAT: Pharus Astronomica.",
    "lions-gate-spaceport": "HU: Oroszlankapu: vedelmi es kozlekedesi nev egyszerre. EN: gate, fortress, and port combined. LAT: Porta Leonis.",
    "senatorum-imperialis": "HU: Birodalmi tanacs. EN: the formal engine of rule. LAT: Senatorum Imperialis.",
    "petitioner-city": "HU: Kervenyezok varosa. EN: a city made from waiting. LAT: Civitas Supplicantium."
  },
  notableById: {
    "imperial-palace": [{ name: "The Emperor of Mankind", role: "sovereign presence at the heart of Terra" }, { name: "Adeptus Custodes", role: "primary guardians of the Palace" }],
    "golden-throne": [{ name: "The Emperor of Mankind", role: "enthroned master of mankind" }, { name: "Adeptus Mechanicus", role: "maintenance rites and impossible repair burdens" }],
    "astronomican": [{ name: "Adeptus Astronomica", role: "operators and wardens of the psychic beacon" }, { name: "Master of the Astronomican", role: "High Lord office tied to the beacon" }],
    "senatorum-imperialis": [{ name: "High Lords of Terra", role: "ruling council of the Imperium" }, { name: "Roboute Guilliman", role: "Imperial Regent in the current era" }],
    "adeptus-custodes-bastion": [{ name: "Captain-General Trajann Valoris", role: "modern commander of the Adeptus Custodes" }, { name: "Shield-Captains", role: "Palace defence command cadres" }],
    "phalanx-anchor": [{ name: "Imperial Fists", role: "Chapter bound to Terra's defence traditions" }, { name: "Phalanx", role: "mobile fortress monastery and void bastion" }]
  },
  locations: [
    {
      id: "imperial-palace",
      name: "Imperial Palace / Himalazia Macro-Fortress",
      shortName: "Imperial Palace",
      subtitle: "Palatium Imperiale",
      lat: 30.8,
      lon: 273.1,
      coordinateConfidence: "approximate: Himalazia palace zone",
      layer: "palace",
      faction: "Adeptus Terra / Imperial Household",
      status: "M41/M42 active throneworld command core",
      loreConfidence: "Verified: Lexicanum Terra, Imperial Palace",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "The Imperial Palace is a continent-scale fortress-city across the Himalazia. It is command centre, shrine-world heart, and final defensive machine of the Imperium."
    },
    {
      id: "golden-throne",
      name: "Golden Throne / Sanctum Imperialis",
      shortName: "Golden Throne",
      subtitle: "Thronus Aureus",
      lat: 30.85,
      lon: 272.95,
      coordinateConfidence: "classified: Palace interior approximation",
      layer: "throne",
      faction: "Adeptus Custodes / Mechanicus throne adepts",
      status: "M41/M42 active and failing sacred machine",
      loreConfidence: "Verified: Lexicanum Golden Throne, Terra",
      sourceKeys: ["lexicanumGoldenThrone", "lexicanumTerra"],
      classified: true,
      text: "The Golden Throne is Terra's most sacred and forbidden machine-sanctum. Access is not travel; it is a chain of seals, authority tests, and lethal guardianship."
    },
    {
      id: "astronomican",
      name: "Astronomican Beacon Complex",
      shortName: "Astronomican",
      subtitle: "Pharus Astronomica",
      lat: 31.2,
      lon: 277.5,
      coordinateConfidence: "approximate: Himalazia beacon complex",
      layer: "throne",
      faction: "Adeptus Astronomica",
      status: "M41/M42 active psychic navigation beacon",
      loreConfidence: "Verified: Lexicanum Astronomican, Forbidden Fortress",
      sourceKeys: ["lexicanumAstronomican", "lexicanumForbiddenFortress"],
      text: "The Astronomican is the psychic lighthouse by which Imperial ships navigate the warp. Around it, sacrifice, machine maintenance, and doctrine become one operating rhythm."
    },
    {
      id: "forbidden-fortress",
      name: "Forbidden Fortress / Hollow Mountain",
      shortName: "Hollow Mountain",
      subtitle: "Fortress of the Astronomican",
      lat: 31.6,
      lon: 278.2,
      coordinateConfidence: "approximate: remote Himalazia complex",
      layer: "throne",
      faction: "Adeptus Astronomica",
      status: "M41/M42 restricted beacon fortress",
      loreConfidence: "Verified: Lexicanum Forbidden Fortress",
      sourceKeys: ["lexicanumForbiddenFortress"],
      classified: true,
      text: "The Forbidden Fortress is the secret mountain complex of the Adeptus Astronomica. Outside it remains stone; inside it becomes chamber, conduit, and sealed psychic engine."
    },
    {
      id: "lions-gate-spaceport",
      name: "Lion's Gate Spaceport",
      shortName: "Lion's Gate",
      subtitle: "Porta Leonis",
      lat: 30.35,
      lon: 273.55,
      coordinateConfidence: "approximate: Palace outer/inner gate interface",
      layer: "transit",
      faction: "Imperial Palace traffic authority",
      status: "M41/M42 active major spaceport",
      loreConfidence: "Verified: Lexicanum Lion's Gate Spaceport",
      sourceKeys: ["lexicanumLionsGate", "lexicanumPalace"],
      text: "Lion's Gate Spaceport is a major Palace transport hub with surface, atmospheric, and void traffic capacity. Its towers and elevators move the lifeblood of the Throneworld."
    },
    {
      id: "eternity-gate",
      name: "Eternity Gate",
      shortName: "Eternity Gate",
      subtitle: "Porta Aeternitatis",
      lat: 30.9,
      lon: 272.8,
      coordinateConfidence: "approximate: Palace inner sanctum gate",
      layer: "palace",
      faction: "Adeptus Custodes",
      status: "M41/M42 active sacred gate",
      loreConfidence: "Referenced in Terra and Palace siege records",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "The Eternity Gate is one of the final names in any route toward the inner sanctums. Pilgrimage, siege, and judgement narrow into a single defended threshold."
    },
    {
      id: "senatorum-imperialis",
      name: "Great Chamber of the Senatorum Imperialis",
      shortName: "Senatorum",
      subtitle: "High Lords' Chamber",
      lat: 30.7,
      lon: 273.28,
      coordinateConfidence: "approximate: Imperial Palace governance district",
      layer: "admin",
      faction: "High Lords of Terra",
      status: "M41/M42 active Imperial ruling chamber",
      loreConfidence: "Verified: Lexicanum Senatorum Imperialis",
      sourceKeys: ["lexicanumSenatorum", "lexicanumTerra"],
      text: "The Senatorum Imperialis is the political heart of the High Lords. Decisions born here become tithes, crusades, pardons, and death warrants across the Imperium."
    },
    {
      id: "adeptus-custodes-bastion",
      name: "Adeptus Custodes Palace Bastion",
      shortName: "Custodes Bastion",
      subtitle: "Aurum Custodia",
      lat: 30.62,
      lon: 273.0,
      coordinateConfidence: "approximate: Palace defence district",
      layer: "military",
      faction: "Adeptus Custodes",
      status: "M41/M42 active elite defence node",
      loreConfidence: "Verified: Lexicanum Adeptus Custodes, Terra",
      sourceKeys: ["lexicanumCustodes", "lexicanumTerra"],
      text: "This bastion represents the Custodes watch over the Palace. Its protocols are not garrison routines; they are the grammar of the Emperor's final defence."
    },
    {
      id: "adeptus-administratum",
      name: "Adeptus Administratum Record Halls",
      shortName: "Administratum",
      subtitle: "Archivum Terrae",
      lat: 29.8,
      lon: 274.1,
      coordinateConfidence: "approximate: Palace bureaucratic sprawl",
      layer: "admin",
      faction: "Adeptus Administratum",
      status: "M41/M42 active Imperial bureaucracy",
      loreConfidence: "Verified headquarters context: Lexicanum Terra",
      sourceKeys: ["lexicanumTerra", "lexicanumSenatorum"],
      text: "The Administratum halls are Terra's bureaucratic nervous system. A lost docket here can become a famine, a delayed regiment, or a forgotten world's extinction."
    },
    {
      id: "ecclesiarchal-palace",
      name: "Ecclesiarchal Palace / Terran Synod Precinct",
      shortName: "Ecclesiarchy",
      subtitle: "Domus Ministorum",
      lat: 41.9,
      lon: 347.5,
      coordinateConfidence: "symbolic approximation: ancient Roma precinct",
      layer: "faith",
      faction: "Adeptus Ministorum",
      status: "M41/M42 active religious power node",
      loreConfidence: "Institution verified: Terra and Senatorum context",
      sourceKeys: ["lexicanumTerra", "lexicanumSenatorum"],
      text: "The Ecclesiarchal precinct is a pressure engine of faith, office, and spectacle. Pilgrims, confessors, shrine writs, and political sermons compress into one holy apparatus."
    },
    {
      id: "petitioner-city",
      name: "Petitioner City",
      shortName: "Petitioner City",
      subtitle: "Civitas Supplicantium",
      lat: 27.8,
      lon: 275.2,
      coordinateConfidence: "approximate: Palace-adjacent pilgrim sprawl",
      layer: "hives",
      faction: "Pilgrims / Adeptus Terra clerks",
      status: "M41/M42 active waiting-city",
      loreConfidence: "Terra pilgrim context, cartographic approximation",
      sourceKeys: ["lexicanumTerra", "lexicanumPalace"],
      text: "Petitioner City is the settlement of waiting that grows in the Palace shadow. Generations can be born, petition, and die before an audience, seal, or refusal arrives."
    },
    {
      id: "merica-hive-belt",
      name: "Merica Hive Belt",
      shortName: "Merica Hives",
      subtitle: "Civitates Mericae",
      lat: 39.5,
      lon: 98.0,
      coordinateConfidence: "approximate: ancient North Merican continental zone",
      layer: "hives",
      faction: "Terran hive authorities",
      status: "M41/M42 active hive and tithe belt",
      loreConfidence: "Old Terra name verified in Lexicanum Terra",
      sourceKeys: ["lexicanumTerra"],
      text: "Merica survives as an Imperial distortion of an ancient name. Its hive belts feed the Throneworld with people, petitions, levy bodies, and endless material demand."
    },
    {
      id: "europa-cardinal-bastions",
      name: "Europa Cardinal Bastions",
      shortName: "Europa Bastions",
      subtitle: "Bastiones Europae",
      lat: 48.8,
      lon: 351.8,
      coordinateConfidence: "approximate: ancient Europa continental zone",
      layer: "faith",
      faction: "Adeptus Ministorum / local hive prefectures",
      status: "M41/M42 active shrine-hive region",
      loreConfidence: "Old Terra name verified in Lexicanum Terra",
      sourceKeys: ["lexicanumTerra"],
      text: "Europa is an old continental name buried beneath shrine-hives, cardinal courts, relic vaults, and disciplined hab sectors that serve Terra's ritual economy."
    },
    {
      id: "phalanx-anchor",
      name: "Phalanx Strategic Anchor",
      shortName: "Phalanx Anchor",
      subtitle: "Praesidium Phalanx",
      lat: 0,
      lon: 320,
      coordinateConfidence: "orbital: representative station longitude",
      layer: "orbital",
      faction: "Imperial Fists",
      status: "mobile orbital fortress, strategic Terra defence asset",
      loreConfidence: "Verified: Lexicanum Phalanx, Terra defence context",
      sourceKeys: ["lexicanumPhalanx", "lexicanumTerra"],
      text: "The Phalanx anchor is a strategic overlay for the fortress-monastery's Terran defence role. It marks the fact that the sky over Terra is never empty."
    },
    {
      id: "orbital-plate-network",
      name: "Terran Orbital Plate Network",
      shortName: "Orbital Plates",
      subtitle: "Corona Defensionis Terrae",
      lat: 0,
      lon: 180,
      coordinateConfidence: "orbital equatorial defence band",
      layer: "orbital",
      faction: "Imperial Navy / Palace defence commands",
      status: "M41/M42 active orbital defence and traffic shell",
      loreConfidence: "Terra orbital defence context, campaign abstraction",
      sourceKeys: ["lexicanumTerra"],
      text: "The orbital plate network is a campaign abstraction for Terra's void shield, gun, dock, and traffic shell. It is armour, customs office, and execution platform in orbit."
    }
  ]
};
