window.MARS_RPG_DATA = {
  CLASSIFIED_PASSKEY: "OMNISSIAH",
  sources: {
    lexicanumMars: "https://wh40k.lexicanum.com/wiki/Mars",
    lexicanumNoctis: "https://wh40k.lexicanum.com/wiki/Noctis_Labyrinthus",
    lexicanumMagma: "https://wh40k.lexicanum.com/wiki/Magma_City",
    lexicanumMoravec: "https://wh40k.lexicanum.com/wiki/Vaults_of_Moravec",
    lexicanumTemple: "https://wh40k.lexicanum.com/wiki/Temple_of_All_Knowledge",
    fandomMars: "https://warhammer40k.fandom.com/wiki/Mars"
  },
  layers: [
    { id: "hives", name: "Hives", icon: "domain", color: "#c5a844" },
    { id: "forges", name: "Forge Temples", icon: "precision_manufacturing", color: "#8b2500" },
    { id: "mines", name: "Mines", icon: "construction", color: "#6b4a2b" },
    { id: "energy", name: "Energy", icon: "bolt", color: "#7f8f5f" },
    { id: "archives", name: "Data / Archives", icon: "database", color: "#7f907f" },
    { id: "military", name: "Military", icon: "security", color: "#c0341a" },
    { id: "orbital", name: "Orbital", icon: "orbit", color: "#a98b2e" }
  ],
  patterns: [
    { id: "north-hive-web", layer: "hives", name: "Northern Hive Belt", latMin: 28, latMax: 72, lonMin: 250, lonMax: 30, pattern: "hex" },
    { id: "tharsis-forge-veins", layer: "forges", name: "Tharsis Forge Mandala", latMin: -24, latMax: 28, lonMin: 80, lonMax: 150, pattern: "cog" },
    { id: "deep-core-mines", layer: "mines", name: "Deep Core Extraction Grid", latMin: -55, latMax: 8, lonMin: 300, lonMax: 70, pattern: "mine" },
    { id: "arcadia-grid", layer: "energy", name: "Arcadia Solar Lattice", latMin: 25, latMax: 62, lonMin: 130, lonMax: 205, pattern: "circuit" },
    { id: "olympus-archive", layer: "archives", name: "Olympus Data Reliquaries", latMin: 6, latMax: 28, lonMin: 122, lonMax: 148, pattern: "data" },
    { id: "solis-redoubt", layer: "military", name: "Solis Defence Grid", latMin: -38, latMax: 4, lonMin: 70, lonMax: 125, pattern: "target" },
    { id: "ring-of-iron", layer: "orbital", name: "Ring of Iron", latMin: -3, latMax: 3, lonMin: 0, lonMax: 360, pattern: "orbital" }
  ],
  locations: [
    {
      id: "olympus-mons",
      name: "Olympus Mons / Fabricator-General Forge Temple",
      shortName: "Olympus Mons",
      subtitle: "Sedes Fabricatoris-General",
      lat: 18.65,
      lon: 133.8,
      coordinateConfidence: "exact surface feature",
      layer: "forges",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active seat of power",
      loreConfidence: "Verified: Lexicanum Mars, Fandom Mars map key",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "The Grand Mountain is the holiest axis of Sacred Mars: forge-city, throne-temple, and seat of the Fabricator-General. Liturgies of dominion roll down its flanks in binharic thunder."
    },
    {
      id: "temple-all-knowledge",
      name: "Temple of All Knowledge / High Altar of Technology",
      shortName: "Temple of All Knowledge",
      subtitle: "Altare Omnis Scientiae",
      lat: 18.9,
      lon: 134.4,
      coordinateConfidence: "approximate: within Olympus Mons complex",
      layer: "archives",
      faction: "Cult Mechanicus",
      status: "M41/M42 active sacred archive",
      loreConfidence: "Verified: Lexicanum Mars, Lexicanum Temple of All Knowledge",
      sourceKeys: ["lexicanumMars", "lexicanumTemple"],
      text: "A vast and ancient repository of Machine Cult knowledge. Every new discovery is offered to its altar, where piston-vaults and noospheric choirs preserve the memory of iron."
    },
    {
      id: "ring-of-iron",
      name: "The Ring of Iron",
      shortName: "Ring of Iron",
      subtitle: "Corona Ferrum Martis",
      lat: 0,
      lon: 0,
      coordinateConfidence: "orbital equatorial band",
      layer: "orbital",
      faction: "Battlefleet Solar / Adeptus Mechanicus",
      status: "M41/M42 active orbital manufactorum",
      loreConfidence: "Verified: Lexicanum Mars",
      sourceKeys: ["lexicanumMars"],
      text: "The equatorial shipyard-halo of Mars. Void-lifts climb from the rusted surface into its docks, and warships are assembled beneath prayers of vacuum and plasma."
    },
    {
      id: "collegia-titanica",
      name: "Collegia Titanica Headquarters",
      shortName: "Collegia Titanica",
      subtitle: "Strategium Titanicus",
      lat: 42,
      lon: 18,
      coordinateConfidence: "cartographic approximate",
      layer: "military",
      faction: "Collegia Titanica",
      status: "M41/M42 active command node",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A command nexus for the god-engines of Mars. Here princeps-vaults and moderati choirs translate planetary threat into titan-scale wrath."
    },
    {
      id: "glaivid-hive",
      name: "Glaivid Hive",
      shortName: "Glaivid Hive",
      subtitle: "Civitas Ferruginea",
      lat: 55,
      lon: 332,
      coordinateConfidence: "cartographic approximate",
      layer: "hives",
      faction: "Martian Hives",
      status: "M41/M42 active hive",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A hive-spire labyrinth of red dust and brass pressure gates. Menials ascend by tithe, augmentation, and obedience to the machine-litany."
    },
    {
      id: "oxygos-hive",
      name: "Oxygos Hive",
      shortName: "Oxygos Hive",
      subtitle: "Hab-Ziggurat Oxygos",
      lat: 48,
      lon: 5,
      coordinateConfidence: "cartographic approximate",
      layer: "hives",
      faction: "Martian Hives",
      status: "M41/M42 active hive",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "Oxygos rises from the northern industrial glow, a layered hive of sealed habs, oxygen tithe-vaults, and catechism-coded transit shafts."
    },
    {
      id: "olympus-undae-hive",
      name: "Olympus Undae Hive",
      shortName: "Olympus Undae Hive",
      subtitle: "Hive of the Rust Dunes",
      lat: 77.5,
      lon: 135,
      coordinateConfidence: "approximate: Olympus Undae region",
      layer: "hives",
      faction: "Martian Hives",
      status: "M41/M42 active hive",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A polar hive anchored in the dune-seas north of Olympus. Its outer shells creak under electrostatic storms and buried manufactorum heat."
    },
    {
      id: "tantalus-hive",
      name: "Tantalus Hive",
      shortName: "Tantalus Hive",
      subtitle: "Civitas Tantalus",
      lat: 34,
      lon: 320,
      coordinateConfidence: "cartographic approximate",
      layer: "hives",
      faction: "Martian Hives",
      status: "M41/M42 active hive",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "Tantalus is a hunger-machine of labor cohorts and sealed factorum clans. Its elevators descend deeper than its spires rise."
    },
    {
      id: "nilosyrtis-hive",
      name: "Nilosyrtis Hive",
      shortName: "Nilosyrtis Hive",
      subtitle: "Nilo-Syrtis Hab Engine",
      lat: 31,
      lon: 288,
      coordinateConfidence: "approximate: Nilosyrtis region",
      layer: "hives",
      faction: "Martian Hives",
      status: "M41/M42 active hive",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A hive grid on the old Nilosyrtis marches. Cogitator census-spirits mark its population as fluctuating, obedient, and useful."
    },
    {
      id: "milancovic-reactor",
      name: "Milancovic Fusion Reactor",
      shortName: "Milancovic Reactor",
      subtitle: "Cor Fusio Septentrionalis",
      lat: 54,
      lon: 148,
      coordinateConfidence: "approximate: Milankovic region",
      layer: "energy",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active energy complex",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A fusion heart beneath northern scarps. Its maintenance choirs recite stellar compression rites while plasma valves burn like caged dawns."
    },
    {
      id: "arcadia-solar",
      name: "Arcadia Solar Collector Fields",
      shortName: "Arcadia Solar Fields",
      subtitle: "Campus Solis Arcadiae",
      lat: 46,
      lon: 170,
      coordinateConfidence: "approximate: Arcadia Planitia",
      layer: "energy",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active energy field",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "Kilometres of gold-black collector vanes drink weak Martian sun and feed forge-temples through buried sanctified conduits."
    },
    {
      id: "omnid-apertura",
      name: "Omnid Apertura",
      shortName: "Omnid Apertura",
      subtitle: "Apertura Omnid",
      lat: 31,
      lon: 210,
      coordinateConfidence: "cartographic approximate",
      layer: "archives",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active data aperture",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A cyclopean data-throat and ritual ingress node. Its inner shutters open only to approved noospheric signatures."
    },
    {
      id: "mareotis-forge",
      name: "Mareotis Forge Temple",
      shortName: "Mareotis Forge",
      subtitle: "Templum Fabricator Mareotis",
      lat: 44,
      lon: 80,
      coordinateConfidence: "cartographic approximate",
      layer: "forges",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active forge temple",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A forge-temple complex whose outer yards glow with heat-bloom and smog. Its product codes are sealed behind priesthood rank."
    },
    {
      id: "acheron-fosse-forges",
      name: "Acheron Fosse Forge Temples",
      shortName: "Acheron Fosse",
      subtitle: "Templa Fossa Acherontis",
      lat: 38,
      lon: 136,
      coordinateConfidence: "approximate: Acheron Fossae",
      layer: "forges",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active forge temples",
      loreConfidence: "Verified: Lexicanum Mars",
      sourceKeys: ["lexicanumMars"],
      text: "Forge-temples straddle the ancient fractures. Servo-haulers descend into the scarps carrying ores, weapons, and silence."
    },
    {
      id: "deep-core-mines",
      name: "Deep Core Mines",
      shortName: "Deep Core Mines",
      subtitle: "Fodinae Cordis Rubri",
      lat: -34,
      lon: 42,
      coordinateConfidence: "cartographic approximate",
      layer: "mines",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active extraction network",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A planetary wound of shafts and pressure-crypts. Ore, relic-alloy, and forbidden thermal signatures rise from the red core."
    },
    {
      id: "navis-assembly-yards",
      name: "Navis Imperialis Assembly Yards",
      shortName: "Navis Assembly Yards",
      subtitle: "Navis Imperialis Fabrica",
      lat: 6,
      lon: 190,
      coordinateConfidence: "cartographic approximate",
      layer: "orbital",
      faction: "Navis Imperialis",
      status: "M41/M42 active assembly yards",
      loreConfidence: "Verified map-key location: Fandom Mars",
      sourceKeys: ["fandomMars"],
      text: "Surface-to-orbit construction yards where hull ribs are blessed before they are lifted into the Ring of Iron."
    },
    {
      id: "esperanos-space-port",
      name: "Esperanos Space Port",
      shortName: "Esperanos Port",
      subtitle: "Portus Esperanos",
      lat: 3,
      lon: 225,
      coordinateConfidence: "cartographic approximate",
      layer: "orbital",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active space port",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A launch plain of red-lit gantries and void-lift anchors. Its traffic is measured in pilgrim ships, mass conveyors, and war materiel."
    },
    {
      id: "deus-manus-space-port",
      name: "Deus Manus Space Port",
      shortName: "Deus Manus Port",
      subtitle: "Portus Manus Dei",
      lat: -6,
      lon: 232,
      coordinateConfidence: "cartographic approximate",
      layer: "orbital",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active space port",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A holy port for heavy void traffic. Its machine-spirits demand incense before every engine ignition."
    },
    {
      id: "mars-docks",
      name: "Navis Imperialis Mars Docks",
      shortName: "Mars Docks",
      subtitle: "Doca Martis",
      lat: 0,
      lon: 242,
      coordinateConfidence: "cartographic approximate",
      layer: "orbital",
      faction: "Navis Imperialis",
      status: "M41/M42 active docks",
      loreConfidence: "Verified map-key location: Fandom Mars",
      sourceKeys: ["fandomMars"],
      text: "The planetary dock interface below the orbital ring. Cargo prayers, plasma warnings, and battlefleet priority orders crowd the vox."
    },
    {
      id: "mondus-terrawatt",
      name: "Mondus Terrawatt II Complex",
      shortName: "Mondus Terrawatt II",
      subtitle: "Complexus Terrawatt",
      lat: -18,
      lon: 105,
      coordinateConfidence: "cartographic approximate",
      layer: "energy",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active energy complex",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A titanic power complex that feeds forge and hive districts. Its safety margins are recited as doctrine, not engineering."
    },
    {
      id: "lybia-montes-forges",
      name: "Lybia Montes Forge Temples",
      shortName: "Lybia Montes Forges",
      subtitle: "Templa Montium Lybiae",
      lat: 0,
      lon: 275,
      coordinateConfidence: "approximate: Libya Montes region",
      layer: "forges",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active forge temples",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "Forge-temples scattered among old highlands. Their manufactoria answer to mountain-deep machine shrines."
    },
    {
      id: "lethe-zone",
      name: "Lethe Zone",
      shortName: "Lethe Zone",
      subtitle: "Zona Lethe",
      lat: -23,
      lon: 280,
      coordinateConfidence: "cartographic approximate",
      layer: "archives",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active restricted zone",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A memory-shadowed administrative and data district. Servitors leaving the zone are routinely scrubbed of route knowledge."
    },
    {
      id: "mondus-gamma",
      name: "Mondus Gamma Forge Temple",
      shortName: "Mondus Gamma",
      subtitle: "Forge of Lukas Chrom",
      lat: -8,
      lon: 104,
      coordinateConfidence: "approximate: Syria Planum / Tharsis",
      layer: "forges",
      faction: "Mechanicum / Adeptus Mechanicus",
      status: "Heresy-era major forge; later status uncertain",
      loreConfidence: "Verified: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A powerful Tharsis forge temple remembered for its Heresy-era output and Techmarine training quality. Current records are incomplete."
    },
    {
      id: "mechavitae-forge",
      name: "Mechavitae Forge Temple",
      shortName: "Mechavitae Forge",
      subtitle: "Templum Mechavitae",
      lat: -36,
      lon: 258,
      coordinateConfidence: "cartographic approximate",
      layer: "forges",
      faction: "Adeptus Mechanicus",
      status: "M41/M42 active forge temple",
      loreConfidence: "Verified map-key location: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A forge-temple associated with bio-mechanical processions and sanctified production rites. Its deeper vaults are not on public transit schemata."
    },
    {
      id: "noctis-labyrinthus",
      name: "Noctis Labyrinthus / Dragon of Mars Classified Zone",
      shortName: "Noctis Labyrinthus",
      subtitle: "Anathemor / Labyrinth of Night",
      lat: -7,
      lon: 102,
      coordinateConfidence: "exact surface feature",
      layer: "military",
      faction: "Adeptus Mechanicus / Ordo-level secrecy",
      status: "M41/M42 quarantined and classified",
      loreConfidence: "Verified: Lexicanum Noctis, Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumNoctis", "lexicanumMars", "fandomMars"],
      classified: true,
      text: "The Labyrinth of Night is officially hostile, contaminated, and spiritually unsound. Deeper truth: the Dragon of Mars is bound beneath the maze, and the redacted wardens do not sleep."
    },
    {
      id: "vaults-moravec",
      name: "Vaults of Moravec",
      shortName: "Moravec Vaults",
      subtitle: "Vaultum Moravec, Heretek Seal",
      lat: -1,
      lon: 112,
      coordinateConfidence: "cartographic approximate",
      layer: "archives",
      faction: "Dark Mechanicum origin / sealed by treaty",
      status: "Heresy-era heretek vault; classified",
      loreConfidence: "Verified: Lexicanum Vaults of Moravec",
      sourceKeys: ["lexicanumMoravec"],
      classified: true,
      traitorSensitive: true,
      text: "A forbidden vault-system founded by Primus Moravec. Opening it released corrupt scrapcode during the Schism of Mars and helped birth the Dark Mechanicum."
    },
    {
      id: "magma-city",
      name: "Magma City / Vulkan Gate Ruins",
      shortName: "Magma City Ruins",
      subtitle: "Civitas Magma, Porta Vulkan",
      lat: -14,
      lon: 120,
      coordinateConfidence: "approximate: south of Arsia Mons",
      layer: "forges",
      faction: "Koriel Zeth loyalist Mechanicum",
      status: "Destroyed in the Horus Heresy; ruins only",
      loreConfidence: "Verified: Lexicanum Magma City",
      sourceKeys: ["lexicanumMagma"],
      text: "Once Koriel Zeth's void-shielded city of lava sluices and noospheric miracles. It died under Heresy fire and its own unleashed magma, leaving Vulkan Gate as memory."
    },
    {
      id: "ascraeus-mons",
      name: "Ascraeus Mons / Legio Tempestus Fortress Ruins",
      shortName: "Ascraeus Mons",
      subtitle: "Fortress of Legio Tempestus",
      lat: 11.9,
      lon: 104.5,
      coordinateConfidence: "exact surface feature",
      layer: "military",
      faction: "Legio Tempestus",
      status: "Heresy-era fortress destroyed during Schism of Mars",
      loreConfidence: "Verified: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      text: "A Tharsis volcano and former fortress of Legio Tempestus. Loyal engine-pride still echoes in the ruin-vox beneath its ash."
    },
    {
      id: "pavonis-mons",
      name: "Pavonis Mons / Legio Mortis Fortress",
      shortName: "Pavonis Mons",
      subtitle: "Traitor Titanicus Historical Site",
      lat: 0.8,
      lon: 112.8,
      coordinateConfidence: "exact surface feature",
      layer: "military",
      faction: "Legio Mortis",
      status: "Heresy-era traitor fortress; status sensitive",
      loreConfidence: "Verified: Lexicanum Mars, Fandom Mars",
      sourceKeys: ["lexicanumMars", "fandomMars"],
      classified: true,
      traitorSensitive: true,
      text: "Pavonis Mons held the Heresy-era fortress of Legio Mortis. Its name remains a red datum in Titanicus archives: death walked here in engine form."
    },
    {
      id: "aries-primus",
      name: "Aries Primus",
      shortName: "Aries Primus",
      subtitle: "Heresy Munitions City",
      lat: 14,
      lon: 70,
      coordinateConfidence: "cartographic approximate",
      layer: "military",
      faction: "Mechanicum",
      status: "Heresy-era second major city; current existence unknown",
      loreConfidence: "Verified: Lexicanum Mars",
      sourceKeys: ["lexicanumMars"],
      text: "Once the second major city of Mars and a colossal source of war munitions. Its Ring of Death defences belong to Heresy records; M41 status is uncertain."
    }
  ]
};
